const CATEGORIES = ['Fintech', 'ML/AI', 'Infrastructure', 'Open Source', 'Web3', 'Platform'];

const EN = {
  NAME: 'ALEKSANDR GRIBAKIN', TAGLINE: '15 Years in Code', SKIP_LINK: 'Skip to content',
  ROLE: 'Lead Full Stack Engineer & System Architect',
  INTRO_SUB: 'Building systems that scale. Leading teams that deliver.',
  SECTION_TITLES: { STATS: 'Impact By The Numbers', CAREER: 'Career Timeline', PROJECTS: 'Projects & Impact', ACHIEVEMENTS: 'Milestones & Recognition' },
  BOOT_LINES: ['DECRYPTING_IDENTITY... OK', 'SCANNING_CREDENTIALS... OK', 'LOADING_PORTFOLIO... OK', 'ESTABLISHING_SECURE_CHANNEL... OK', 'WELCOME://ALEKSANDR.GRIBAKIN'],
  STATS: [
    { label: 'Years in Production', value: '15+' }, { label: 'Systems Architected', value: '40+' },
    { label: 'Teams Led', value: '7' }, { label: 'Open Source Repos', value: '24' },
    { label: 'Countries Deployed', value: '14' }, { label: 'M Users Served', value: '12M+' },
  ],
  CAREER: [
    { period: '2023–2026', role: 'Principal Engineer', company: 'Tech Corp', desc: 'Architected multi-region payment mesh handling $4B+ annually. Led 20+ engineers across 3 squads. Reduced infra costs 42% via K8s optimization.' },
    { period: '2020–2023', role: 'Head of Engineering', company: 'FinScale', desc: 'Built team 2→18. Delivered real-time fraud detection at 8K TPS. Migrated monolith→60 microservices, zero downtime.' },
    { period: '2017–2020', role: 'Tech Lead / Architect', company: 'DataStream', desc: 'Designed event-driven data lake processing 500TB/day. Spark→Rust: 12x throughput gain. Team of 10.' },
    { period: '2014–2017', role: 'Senior Full Stack Engineer', company: 'WebScale', desc: 'Built SaaS for 500K+ businesses. PHP→Go+React: 8x latency improvement. Mentored 6→senior.' },
    { period: '2011–2014', role: 'Full Stack Developer', company: 'StartupLab', desc: 'Shipped 12 products in 3 years. Full ownership DB→CSS. First hire through Series A exit.' },
    { period: '2007–2011', role: 'B.S. Computer Science', company: 'University of Technology', desc: 'Graduated with honors. Thesis on distributed consensus protocols. Focus: algorithms, distributed systems, and low-level programming.' },
  ],
  CATEGORIES: ['All', ...CATEGORIES],
  CATEGORY_LABELS: ['All', 'Fintech', 'ML/AI', 'Infrastructure', 'Open Source', 'Web3', 'Platform'],
  PROJECTS: [
    // --- Fintech (7) ---
    { id: 'payment-mesh', name: 'Global Payment Mesh', cat: 'Fintech', tag: 'Platform', stack: 'Go, Temporal, Postgres, Kafka, Kubernetes', desc: 'Multi-region payment orchestration. $4B+ annual volume, 99.999% uptime across 14 regions. Sub-10ms p99 latency at 50K TPS.', metric: '$4B+ / 14 regions / 50K TPS' },
    { id: 'fraud-engine', name: 'Real-Time Fraud Engine', cat: 'Fintech', tag: 'ML/AI', stack: 'Python, PyTorch, Kafka, Redis, FastAPI', desc: 'ML fraud detection at 8K TPS. 99.2% precision, 40ms inference, $12M saved in fraud loss Y1.', metric: '8K TPS / 99.2% precision / $12M saved' },
    { id: 'audit-log', name: 'Immutable Audit Pipeline', cat: 'Fintech', tag: 'Infrastructure', stack: 'Rust, Kafka, ClickHouse, S3, Grafana', desc: 'Immutable audit log for regulated fintech. 1M events/sec, 5-year retention, sub-200ms queries. SOC2/PCI compliant.', metric: '1M events/s / 5yr / 200ms queries' },
    { id: 'compliance', name: 'Compliance Engine', cat: 'Fintech', tag: 'Platform', stack: 'Go, PostgreSQL, Temporal, OpenPolicyAgent', desc: 'Policy-driven compliance engine. 4K rules evaluated per transaction in <5ms. Automated regulatory reporting.', metric: '4K rules / <5ms eval per tx' },
    { id: 'ledger', name: 'Double-Entry Ledger Service', cat: 'Fintech', tag: 'Platform', stack: 'Rust, SQLite, gRPC, NATS, Prometheus', desc: 'Embedded ledger for payment flows. 200K entries/sec per node, strict ACID, real-time reconciliation.', metric: '200K entries/s / ACID' },
    { id: 'billing', name: 'Usage-Based Billing Platform', cat: 'Fintech', tag: 'Platform', stack: 'Go, Stripe, Redis, Postgres, Kafka', desc: 'Real-time usage metering + billing. 10K metering events/sec, 99.99% invoice accuracy, sub-minute latency.', metric: '10K events/s / 99.99% accuracy' },
    { id: 'kyc-orch', name: 'KYC Orchestrator', cat: 'Fintech', tag: 'Platform', stack: 'TypeScript, Node, DocumentDB, AWS Textract, Step Functions', desc: 'Document verification pipeline. 300K+ verifications, 40% faster than incumbent, 95% auto-approval rate.', metric: '300K verified / 95% auto-approval' },
    // --- ML/AI (5) ---
    { id: 'ml-platform', name: 'ML Training Platform', cat: 'ML/AI', tag: 'Platform', stack: 'Python, PyTorch, Ray, AWS, Docker', desc: 'Internal ML platform for 200+ data scientists. Distributed training, auto-hptune, model registry. 3x team velocity.', metric: '200+ scientists / 3x velocity' },
    { id: 'feature-store', name: 'Real-Time Feature Store', cat: 'ML/AI', tag: 'Infrastructure', stack: 'Go, Redis, Kafka, S3, Flink', desc: 'Online/offline feature serving. p99 2ms online retrieval, 10K features, 1TB/day throughput.', metric: '2ms p99 / 10K features / 1TB/day' },
    { id: 'model-mesh', name: 'Model Serving Mesh', cat: 'ML/AI', tag: 'Infrastructure', stack: 'Python, Triton, K8s, Envoy, Prometheus', desc: 'Multi-model serving mesh. 50+ model types, auto-scaling to zero, sub-10ms p50 inference.', metric: '50+ models / auto-scale / 10ms p50' },
    { id: 'nlp-pipe', name: 'NLP Pipeline', cat: 'ML/AI', tag: 'Platform', stack: 'Python, Transformers, Elasticsearch, FastAPI, Docker', desc: 'Document NLP pipeline. 10M docs/day, NER + classification + summarization, 94% F1.', metric: '10M docs/day / 94% F1' },
    { id: 'anomaly', name: 'Anomaly Detection System', cat: 'ML/AI', tag: 'Platform', stack: 'Python, Prophet, TimescaleDB, Grafana, Kafka', desc: 'Real-time anomaly detection for financial metrics. 5K metric streams, <30s alert latency, 96% precision.', metric: '5K streams / <30s alerts / 96% precision' },
    // --- Infrastructure (6) ---
    { id: 'data-lake', name: 'Distributed Data Lake', cat: 'Infrastructure', tag: 'Data', stack: 'Rust, Kafka, S3, Iceberg, Trino', desc: '500TB/day streaming data lake. Custom Rust pipeline replaced Spark — 12x throughput, 80% less infra cost.', metric: '500TB/day / 12x / 80% cost reduction' },
    { id: 'migration-kit', name: 'Enterprise Migration Toolkit', cat: 'Infrastructure', tag: 'Platform', stack: 'Go, Envoy, Kafka, Terraform, Prometheus', desc: 'Zero-downtime monolith→microservices framework. 6 enterprise engagements, 150+ services migrated.', metric: '150+ services / 0-downtime' },
    { id: 'k8s-operators', name: 'Kubernetes Operator Suite', cat: 'Infrastructure', tag: 'Open Source', stack: 'Go, K8s, Prometheus, Helm, Cert-Manager', desc: '6 custom operators for DB provisioning, canary deployments, secret rotation. 1K+ GitHub stars.', metric: '6 operators / 1K+ ★' },
    { id: 'cicd', name: 'Internal CI/CD Platform', cat: 'Infrastructure', tag: 'Platform', stack: 'Go, Tekton, ArgoCD, Vault, Harbor', desc: 'Self-serve CI/CD used by 40+ teams. 2K builds/day, 8min median build time, 99.9% uptime.', metric: '40+ teams / 2K builds/day' },
    { id: 'service-mesh', name: 'Multi-Cluster Service Mesh', cat: 'Infrastructure', tag: 'Platform', stack: 'Go, Istio, Envoy, Grafana, Kiali', desc: 'Multi-cluster mesh across 3 regions. mTLS, traffic shifting, 95% reduction in cross-team incidents.', metric: '3 regions / mTLS / -95% incidents' },
    { id: 'paas', name: 'Multi-Cloud Application Platform', cat: 'Infrastructure', tag: 'Platform', stack: 'Go, Terraform, Pulumi, Crossplane, K8s', desc: 'Self-serve platform on AWS/GCP/Azure. Dev→prod in 12min vs 2 days prior. 200+ apps running.', metric: '12min deploy / 200+ apps' },
    // --- Open Source (5) ---
    { id: 'kubedbg', name: 'kubectl-debugger', cat: 'Open Source', tag: 'CLI', stack: 'Go, K8s, Cobra, Docker', desc: 'Interactive K8s Pod debugging CLI. 2.4K★, 300+ forks, used by 50+ companies including 2 FAANG.', metric: '2.4K★ / 50+ companies' },
    { id: 'apitest', name: 'api-test-framework', cat: 'Open Source', tag: 'CLI', stack: 'TypeScript, Node, OpenAPI, Axios', desc: 'Declarative API testing framework. 1.8K★, 200+ forks, 10K+ npm downloads/month.', metric: '1.8K★ / 10K+ npm/mo' },
    { id: 'dbmate', name: 'dbmate-pro', cat: 'Open Source', tag: 'CLI', stack: 'Go, PostgreSQL, MySQL, SQLite, ClickHouse', desc: 'Database migration tool with multi-DB support, dry-run, rollback, and CI integration. 1.2K★.', metric: '1.2K★ / multi-DB' },
    { id: 'jsval', name: 'json-schema-validator', cat: 'Open Source', tag: 'Library', stack: 'Rust, WASM, JSON Schema, Node', desc: 'High-performance JSON Schema validator in Rust→WASM. 5x faster than JS alternatives. 800★.', metric: '5x faster / 800★' },
    { id: 'tui-kit', name: 'terminal-ui-kit', cat: 'Open Source', tag: 'Library', stack: 'TypeScript, Ink, React, Node', desc: 'React-based TUI component library for CLI apps. Tables, forms, spinners, progress bars. 1.5K★.', metric: '1.5K★ / 12 components' },
    // --- Web3 (4) ---
    { id: 'did', name: 'Decentralized Identity Protocol', cat: 'Web3', tag: 'Protocol', stack: 'Solidity, Go, IPFS, The Graph, Next.js', desc: 'ZK-proof identity layer for DeFi. 300K+ identities, 60% lower KYC costs. Audited by Trail of Bits.', metric: '300K identities / -60% KYC cost' },
    { id: 'defi-analytics', name: 'DeFi Analytics Platform', cat: 'Web3', tag: 'Platform', stack: 'Python, Web3.py, Postgres, Dune, GraphQL', desc: 'On-chain analytics for 15 protocols. Real-time TVL, volume, wallet tracking. 50 dashboards.', metric: '15 protocols / 50 dashboards' },
    { id: 'nft-infra', name: 'NFT Infrastructure Suite', cat: 'Web3', tag: 'Infrastructure', stack: 'Go, NFT.Storage, IPFS, Alchemy, Redis', desc: 'NFT minting + metadata infrastructure. 500K+ NFTs minted, sub-100ms metadata serving, 99.9% uptime.', metric: '500K+ NFTs / 99.9% uptime' },
    { id: 'dao-govern', name: 'DAO Governance Toolkit', cat: 'Web3', tag: 'Platform', stack: 'Solidity, TypeScript, Snapshot, The Graph', desc: 'Off-chain + on-chain governance suite. 10 DAOs live, 200K+ proposals processed, 75% avg participation.', metric: '10 DAOs / 200K proposals' },
    // --- Platform (5) ---
    { id: 'saas-engine', name: 'Multi-Tenant SaaS Engine', cat: 'Platform', tag: 'Platform', stack: 'Go, React, Postgres, Redis, Terraform', desc: 'Self-serve SaaS powering 500K+ businesses. Multi-tenant isolation, usage billing, real-time analytics. 99.99% SLA.', metric: '500K+ tenants / 99.99% SLA' },
    { id: 'collab-engine', name: 'Real-Time Collaboration Engine', cat: 'Platform', tag: 'Platform', stack: 'TypeScript, CRDTs, WebSockets, ScyllaDB, Redis', desc: 'CRDT-based sync engine. 10K concurrent editors, sub-50ms conflict resolution. Powered competitor to Figma.', metric: '10K concurrent / <50ms sync' },
    { id: 'event-sourcing', name: 'Event Sourcing Platform', cat: 'Platform', tag: 'Infrastructure', stack: 'Go, Kafka, Postgres, Debezium, Kafka Connect', desc: 'Event sourcing + CQRS platform. 500+ event types, 100K events/s, exactly-once semantics.', metric: '500 types / 100K events/s' },
    { id: 'api-gateway', name: 'Unified API Gateway', cat: 'Platform', tag: 'Infrastructure', stack: 'Go, Envoy, Redis, OpenAPI, OAuth2', desc: 'API gateway for 200+ microservices. Rate limiting, auth, caching, circuit breaking. 200K req/s per node.', metric: '200 services / 200K req/s' },
    { id: 'dev-portal', name: 'Internal Developer Portal', cat: 'Platform', tag: 'Platform', stack: 'React, Backstage, TypeScript, GraphQL, PostgreSQL', desc: 'Backstage-based developer portal. 40+ plugins, 200 services cataloged, 1K+ daily active engineers.', metric: '40 plugins / 1K+ daily engineers' },
  ],
  ACHIEVEMENTS: [
    { year: '2026', title: 'Conference Keynote — QCon London', desc: '"Building Resilient Distributed Systems" — 2,500+ attendees, 97% session rating. Invited speaker.' },
    { year: '2025', title: 'KubeCon NA Speaker', desc: '"Running Go Workflows at Scale" — 1,200+ attendees, 94% session rating.' },
    { year: '2024', title: 'Published — ACM Queue', desc: 'Authored "Event-Driven Architectures in Fintech". 40+ citations, featured on cover.' },
    { year: '2023', title: 'Patent — US-11789045', desc: 'Real-time fraud detection using temporal graph neural networks.' },
    { year: '2022', title: 'OSS Launch — K8s Debugger', desc: 'kubectl plugin hit 1K★ in 72 hours. 2.4K★ current. Used by 50+ companies.' },
    { year: '2021', title: 'Lead — Architecture Committee', desc: 'Led 12-squad architecture review board. Set org-wide tech standards.' },
    { year: '2019', title: 'DevOpsDays Speaker', desc: '"Migrating 50 Microservices Without a Single Pager" — highest-rated talk.' },
    { year: '2016', title: 'First Team Lead Role', desc: 'Promoted to lead 4 engineers. Shipped first SaaS product in 4 months.' },
    { year: '2011', title: 'First Production Commit', desc: 'A PHP app. It worked. Mostly. We all start somewhere.' },
  ],
  CTA_TITLE: 'Initiate Consult',
  CTA_SUB: 'Ready to build something extraordinary? One message starts the conversation.',
  FORM: { NAME: 'Your Name', EMAIL: 'Email Address', MESSAGE: 'Describe your project...', SUBMIT: 'Initiate Consult', SUCCESS: '▸ Message transmitted. I will reach out shortly.', PLACEHOLDER_NAME: 'Your name, or your best alias', PLACEHOLDER_EMAIL: 'where pixels meet purpose', PLACEHOLDER_MSG: 'Product, team, dream — paint the picture...' },
  FORM_ERRORS: {
    NAME_REQUIRED: 'Enter your name',
    NAME_MIN: 'Name must be at least 2 characters',
    NAME_MAX: 'Name is too long',
    NAME_PATTERN: 'Name contains invalid characters',
    EMAIL_REQUIRED: 'Enter your email',
    EMAIL_INVALID: 'That does not look like an email',
    EMAIL_PATTERN: 'That does not look like an email',
    MSG_REQUIRED: 'Describe your project briefly',
    MSG_MIN: 'Message must be at least 10 characters',
    MSG_MAX: 'Message is too long (max 2000)',
    NETWORK: 'Network error. Try again later.',
    RATE_LIMIT: 'Slow down. One message at a time.',
  },
  _PAGE_404: {
    TITLE: '404 — Page Not Found',
    SUB: 'This route does not exist.',
    CTA: 'Return Home',
  },
  COFFEE: { TITLE: '☕ Buy me a coffee', NETWORK: 'USDT TRC-20', COPY: 'Copy Address', DONE: '✓ Copied', CLOSE: 'Close' },
  DETAIL: { BACK: 'Back', BACK_CAREER: 'Back to Career', BACK_ACH: 'Back to Achievements', NOT_FOUND: 'not found', KEY_METRICS: 'Key Metrics', FEATURES: 'Features', TECH_STACK: 'Tech Stack', KEY_ACH: 'Key Achievements', TYPE_PROJECT: 'Project', TYPE_CAREER: 'Career', TYPE_ACH: 'Achievement' },
};

const RU = {
  NAME: 'АЛЕКСАНДР ГРИБАКИН', TAGLINE: '15 лет в коде', SKIP_LINK: 'Перейти к содержанию',
  ROLE: 'Lead Full Stack Engineer & System Architect',
  INTRO_SUB: 'Строю системы, которые масштабируются. Веду команды, которые доставляют.',
  SECTION_TITLES: { STATS: 'Влияние в цифрах', CAREER: 'Карьерный путь', PROJECTS: 'Проекты и влияние', ACHIEVEMENTS: 'Вехи и признание' },
  BOOT_LINES: ['ДЕШИФРОВКА_ЛИЧНОСТИ... OK', 'ПРОВЕРКА_ПОЛНОМОЧИЙ... OK', 'ЗАГРУЗКА_ПОРТФОЛИО... OK', 'УСТАНОВКА_БЕЗОПАСНОГО_КАНАЛА... OK', 'ДОБРО_ПОЖАЛОВАТЬ://АЛЕКСАНДР.ГРИБАКИН'],
  STATS: [
    { label: 'Лет в продакшене', value: '15+' }, { label: 'Спроектировано систем', value: '40+' },
    { label: 'Команд под руководством', value: '7' }, { label: 'Open Source репозиториев', value: '24' },
    { label: 'Стран развертывания', value: '14' }, { label: 'Обслужено пользователей', value: '12M+' },
  ],
  CAREER: [
    { period: '2023–2026', role: 'Principal Engineer', company: 'Tech Corp', desc: 'Спроектировал мультирегиональную платежную mesh с оборотом $4B+/год. Руководил 20+ инженерами. Сократил расходы на инфраструктуру на 42%.' },
    { period: '2020–2023', role: 'Head of Engineering', company: 'FinScale', desc: 'Собрал команду 2→18 человек. Система фрод-детекции в реальном времени — 8K TPS. Мигрировал монолит→60 микросервисов без downtime.' },
    { period: '2017–2020', role: 'Tech Lead / Архитектор', company: 'DataStream', desc: 'Спроектировал data lake на 500TB/день. Spark→Rust: прирост производительности в 12x. Команда 10 человек.' },
    { period: '2014–2017', role: 'Senior Full Stack Engineer', company: 'WebScale', desc: 'Построил SaaS-платформу для 500K+ бизнесов. PHP→Go+React: ускорение в 8x. Вырастил 6 джунов до сеньоров.' },
    { period: '2011–2014', role: 'Full Stack Developer', company: 'StartupLab', desc: 'Запустил 12 продуктов за 3 года. Полная ответственность: БД→CSS. Первый наемный сотрудник, прошли до Series A.' },
    { period: '2007–2011', role: 'B.S. Прикладная математика и информатика', company: 'University of Technology', desc: 'Окончил с отличием. Дипломная работа по распределенным протоколам консенсуса. Фокус: алгоритмы, распределенные системы, низкоуровневое программирование.' },
  ],
  CATEGORIES: ['All', ...CATEGORIES],
  CATEGORY_LABELS: ['Все', 'Fintech', 'ML/AI', 'Инфраструктура', 'Open Source', 'Web3', 'Платформа'],
  PROJECTS: [
    { id: 'payment-mesh', name: 'Global Payment Mesh', cat: 'Fintech', tag: 'Платформа', stack: 'Go, Temporal, Postgres, Kafka, Kubernetes', desc: 'Мультирегиональная платежная система. $4B+/год, 99.999% аптайм, 14 регионов. p99 <10ms при 50K TPS.', metric: '$4B+ / 14 регионов / 50K TPS' },
    { id: 'fraud-engine', name: 'Real-Time Fraud Engine', cat: 'Fintech', tag: 'ML/AI', stack: 'Python, PyTorch, Kafka, Redis, FastAPI', desc: 'ML детекция фрода на 8K TPS. 99.2% точность, 40ms инференс. $12M сохранено в первый год.', metric: '8K TPS / 99.2% / $12M сохранено' },
    { id: 'audit-log', name: 'Immutable Audit Pipeline', cat: 'Fintech', tag: 'Инфра', stack: 'Rust, Kafka, ClickHouse, S3, Grafana', desc: 'Иммутабельный аудит-лог. 1M событий/сек, хранение 5 лет, запросы до 200ms. SOC2/PCI.', metric: '1M событий/с / 5 лет / 200ms' },
    { id: 'compliance', name: 'Compliance Engine', cat: 'Fintech', tag: 'Платформа', stack: 'Go, PostgreSQL, Temporal, OpenPolicyAgent', desc: 'Policy-driven система комплаенса. 4K правил на транзакцию за <5ms. Автоматическая регуляторная отчетность.', metric: '4K правил / <5ms' },
    { id: 'ledger', name: 'Double-Entry Ledger Service', cat: 'Fintech', tag: 'Платформа', stack: 'Rust, SQLite, gRPC, NATS, Prometheus', desc: 'Встраиваемый ledger для платежей. 200K записей/сек на ноду, строгий ACID, сверка в реальном времени.', metric: '200K записей/с / ACID' },
    { id: 'billing', name: 'Usage-Based Billing Platform', cat: 'Fintech', tag: 'Платформа', stack: 'Go, Stripe, Redis, Postgres, Kafka', desc: 'Биллинг на основе потребления. 10K событий/сек, точность инвойсов 99.99%, задержка <1 мин.', metric: '10K событий/с / 99.99%' },
    { id: 'kyc-orch', name: 'KYC Orchestrator', cat: 'Fintech', tag: 'Платформа', stack: 'TypeScript, Node, DocumentDB, AWS Textract, Step Functions', desc: 'Конвейер верификации документов. 300K+ проверок, на 40% быстрее конкурентов, 95% авто-одобрение.', metric: '300K+ / 95% авто-одобрение' },
    { id: 'ml-platform', name: 'ML Training Platform', cat: 'ML/AI', tag: 'Платформа', stack: 'Python, PyTorch, Ray, AWS, Docker', desc: 'ML платформа для 200+ дата-сайентистов. Распределенное обучение, авто-hptune, registry моделей. x3 скорость.', metric: '200+ ученых / x3 скорость' },
    { id: 'feature-store', name: 'Real-Time Feature Store', cat: 'ML/AI', tag: 'Инфра', stack: 'Go, Redis, Kafka, S3, Flink', desc: 'Online/offline feature serving. p99 2ms online retrieval, 10K фич, 1TB/день пропускная способность.', metric: '2ms p99 / 10K фич / 1TB/день' },
    { id: 'model-mesh', name: 'Model Serving Mesh', cat: 'ML/AI', tag: 'Инфра', stack: 'Python, Triton, K8s, Envoy, Prometheus', desc: 'Multi-model serving mesh. 50+ типов моделей, авто-масштабирование до нуля, p50 <10ms.', metric: '50+ моделей / <10ms p50' },
    { id: 'nlp-pipe', name: 'NLP Pipeline', cat: 'ML/AI', tag: 'Платформа', stack: 'Python, Transformers, Elasticsearch, FastAPI, Docker', desc: 'Пайплайн NLP для документов. 10M док/день, NER+классификация+суммаризация. F1 94%.', metric: '10M док/день / 94% F1' },
    { id: 'anomaly', name: 'Anomaly Detection System', cat: 'ML/AI', tag: 'Платформа', stack: 'Python, Prophet, TimescaleDB, Grafana, Kafka', desc: 'Аномалии для финансовых метрик. 5K потоков, оповещения <30с, точность 96%.', metric: '5K потоков / <30с / 96%' },
    { id: 'data-lake', name: 'Distributed Data Lake', cat: 'Infrastructure', tag: 'Данные', stack: 'Rust, Kafka, S3, Iceberg, Trino', desc: '500TB/день streaming data lake. Rust пайплайн заменил Spark — 12x скорость, -80% затрат.', metric: '500TB/день / 12x / -80% затрат' },
    { id: 'migration-kit', name: 'Enterprise Migration Toolkit', cat: 'Infrastructure', tag: 'Платформа', stack: 'Go, Envoy, Kafka, Terraform, Prometheus', desc: 'Zero-downtime фреймворк миграции монолитов. 6 enterprise проектов, 150+ сервисов.', metric: '150+ сервисов / zero downtime' },
    { id: 'k8s-operators', name: 'Kubernetes Operator Suite', cat: 'Infrastructure', tag: 'Open Source', stack: 'Go, K8s, Prometheus, Helm, Cert-Manager', desc: '6 кастомных операторов для БД, canary деплоев, ротации секретов. 1K+ звезд GitHub.', metric: '6 операторов / 1K+ ★' },
    { id: 'cicd', name: 'Internal CI/CD Platform', cat: 'Infrastructure', tag: 'Платформа', stack: 'Go, Tekton, ArgoCD, Vault, Harbor', desc: 'Self-serve CI/CD для 40+ команд. 2K сборок/день, медиана 8 мин, аптайм 99.9%.', metric: '40+ команд / 2K сборок/день' },
    { id: 'service-mesh', name: 'Multi-Cluster Service Mesh', cat: 'Infrastructure', tag: 'Платформа', stack: 'Go, Istio, Envoy, Grafana, Kiali', desc: 'Multi-cluster mesh в 3 регионах. mTLS, трафик-шифтинг, -95% инцидентов между командами.', metric: '3 региона / mTLS / -95%' },
    { id: 'paas', name: 'Multi-Cloud Application Platform', cat: 'Infrastructure', tag: 'Платформа', stack: 'Go, Terraform, Pulumi, Crossplane, K8s', desc: 'Self-serve платформа на AWS/GCP/Azure. Разработка→прод за 12 мин вместо 2 дней. 200+ приложений.', metric: '12 мин / 200+ приложений' },
    { id: 'kubedbg', name: 'kubectl-debugger', cat: 'Open Source', tag: 'CLI', stack: 'Go, K8s, Cobra, Docker', desc: 'Интерактивная отладка Pod в K8s. 2.4K★, 300+ форков, используется 50+ компаниями.', metric: '2.4K★ / 50+ компаний' },
    { id: 'apitest', name: 'api-test-framework', cat: 'Open Source', tag: 'CLI', stack: 'TypeScript, Node, OpenAPI, Axios', desc: 'Декларативный фреймворк тестирования API. 1.8K★, 10K+ npm загрузок/мес.', metric: '1.8K★ / 10K+ npm/мес' },
    { id: 'dbmate', name: 'dbmate-pro', cat: 'Open Source', tag: 'CLI', stack: 'Go, PostgreSQL, MySQL, SQLite, ClickHouse', desc: 'Миграции БД с multi-DB поддержкой, dry-run, откатом и CI интеграцией. 1.2K★.', metric: '1.2K★ / multi-DB' },
    { id: 'jsval', name: 'json-schema-validator', cat: 'Open Source', tag: 'Библиотека', stack: 'Rust, WASM, JSON Schema, Node', desc: 'Высокопроизводительный валидатор JSON Schema в Rust→WASM. В 5x быстрее JS аналогов.', metric: '5x быстрее / 800★' },
    { id: 'tui-kit', name: 'terminal-ui-kit', cat: 'Open Source', tag: 'Библиотека', stack: 'TypeScript, Ink, React, Node', desc: 'React TUI библиотека для CLI приложений. Таблицы, формы, спиннеры, прогресс-бары. 1.5K★.', metric: '1.5K★ / 12 компонентов' },
    { id: 'did', name: 'Decentralized Identity Protocol', cat: 'Web3', tag: 'Протокол', stack: 'Solidity, Go, IPFS, The Graph, Next.js', desc: 'ZK-proof слой идентификации для DeFi. 300K+ личностей, -60% стоимости KYC. Аудировано Trail of Bits.', metric: '300K+ / -60% KYC' },
    { id: 'defi-analytics', name: 'DeFi Analytics Platform', cat: 'Web3', tag: 'Платформа', stack: 'Python, Web3.py, Postgres, Dune, GraphQL', desc: 'Аналитика on-chain для 15 протоколов. TVL, объемы, кошельки в реальном времени. 50 дашбордов.', metric: '15 протоколов / 50 дашбордов' },
    { id: 'nft-infra', name: 'NFT Infrastructure Suite', cat: 'Web3', tag: 'Инфра', stack: 'Go, NFT.Storage, IPFS, Alchemy, Redis', desc: 'Инфраструктура минта + метаданных NFT. 500K+ NFT, metadata <100ms, аптайм 99.9%.', metric: '500K+ NFT / 99.9% uptime' },
    { id: 'dao-govern', name: 'DAO Governance Toolkit', cat: 'Web3', tag: 'Платформа', stack: 'Solidity, TypeScript, Snapshot, The Graph', desc: 'Набор инструментов управления DAO. 10 DAO в продакшене, 200K+ предложений, явка 75%.', metric: '10 DAO / 200K предложений' },
    { id: 'saas-engine', name: 'Multi-Tenant SaaS Engine', cat: 'Platform', tag: 'Платформа', stack: 'Go, React, Postgres, Redis, Terraform', desc: 'Self-serve SaaS для 500K+ бизнесов. Multi-tenant изоляция, биллинг, аналитика. 99.99% SLA.', metric: '500K+ / 99.99% SLA' },
    { id: 'collab-engine', name: 'Real-Time Collaboration Engine', cat: 'Platform', tag: 'Платформа', stack: 'TypeScript, CRDTs, WebSockets, ScyllaDB, Redis', desc: 'CRDT движок синхронизации. 10K редакторов, разрешение конфликтов <50ms. Аналог Figma.', metric: '10K конк. / <50ms' },
    { id: 'event-sourcing', name: 'Event Sourcing Platform', cat: 'Platform', tag: 'Инфра', stack: 'Go, Kafka, Postgres, Debezium, Kafka Connect', desc: 'Event sourcing + CQRS. 500+ типов событий, 100K событий/с, exactly-once.', metric: '500 типов / 100K/с' },
    { id: 'api-gateway', name: 'Unified API Gateway', cat: 'Platform', tag: 'Инфра', stack: 'Go, Envoy, Redis, OpenAPI, OAuth2', desc: 'API gateway для 200+ микросервисов. Rate limiting, auth, кэширование, circuit breaker. 200K req/с.', metric: '200 сервисов / 200K req/с' },
    { id: 'dev-portal', name: 'Internal Developer Portal', cat: 'Platform', tag: 'Платформа', stack: 'React, Backstage, TypeScript, GraphQL, PostgreSQL', desc: 'Backstage портал разработчика. 40+ плагинов, 200 сервисов в каталоге, 1K+ активных инженеров в день.', metric: '40 плагинов / 1K+ инженеров' },
  ],
  ACHIEVEMENTS: [
    { year: '2026', title: 'Ключевой доклад — QCon London', desc: '"Building Resilient Distributed Systems" — 2,500+ участников, рейтинг 97%. Приглашенный спикер.' },
    { year: '2025', title: 'Доклад — KubeCon NA', desc: '"Running Go Workflows at Scale" — 1,200+ участников, рейтинг 94%.' },
    { year: '2024', title: 'Публикация — ACM Queue', desc: 'Автор "Event-Driven Architectures in Fintech". 40+ цитирований, обложка выпуска.' },
    { year: '2023', title: 'Патент — US-11789045', desc: 'Детекция фрода в реальном времени с использованием темпоральных графовых нейросетей.' },
    { year: '2022', title: 'OSS Релиз — K8s Debugger', desc: 'kubectl плагин набрал 1K★ за 72 часа. Текущий счет 2.4K★. Используется 50+ компаниями.' },
    { year: '2021', title: 'Руководитель — Архитектурный Комитет', desc: 'Возглавил комитет из 12 команд. Установил стандарты технологического стека.' },
    { year: '2019', title: 'Доклад — DevOpsDays', desc: '"Миграция 50 микросервисов без единой аварии" — лучший доклад конференции.' },
    { year: '2016', title: 'Первая роль Team Lead', desc: 'Повышение до лида 4 инженеров. Запуск первого SaaS продукта за 4 месяца.' },
    { year: '2011', title: 'Первый коммит в продакшен', desc: 'PHP приложение. Работало. Почти. Мы все с чего-то начинали.' },
  ],
  CTA_TITLE: 'Начать консультацию',
  CTA_SUB: 'Готовы построить нечто экстраординарное? Одно сообщение запускает разговор.',
  FORM: { NAME: 'Ваше Имя', EMAIL: 'Email Адрес', MESSAGE: 'Опишите ваш проект...', SUBMIT: 'Начать консультацию', SUCCESS: '▸ Сообщение отправлено. Я свяжусь с вами в ближайшее время.', PLACEHOLDER_NAME: 'Имя или лучший псевдоним', PLACEHOLDER_EMAIL: 'туда, где живёт идея', PLACEHOLDER_MSG: 'Продукт, команда, мечта — опишите картину...' },
  FORM_ERRORS: {
    NAME_REQUIRED: 'Введите ваше имя',
    NAME_MIN: 'Имя должно содержать минимум 2 символа',
    NAME_MAX: 'Имя слишком длинное',
    NAME_PATTERN: 'Имя содержит недопустимые символы',
    EMAIL_REQUIRED: 'Введите ваш email',
    EMAIL_INVALID: 'Это не похоже на email',
    EMAIL_PATTERN: 'Это не похоже на email',
    MSG_REQUIRED: 'Опишите ваш проект кратко',
    MSG_MIN: 'Сообщение должно содержать минимум 10 символов',
    MSG_MAX: 'Сообщение слишком длинное (макс. 2000)',
    NETWORK: 'Ошибка сети. Попробуйте позже.',
    RATE_LIMIT: 'Не так быстро. По одному сообщению.',
  },
  _PAGE_404: {
    TITLE: '404 — Страница не найдена',
    SUB: 'Этот маршрут не существует.',
    CTA: 'Вернуться на главную',
  },
  COFFEE: { TITLE: '☕ Угостить кофе', NETWORK: 'USDT TRC-20', COPY: 'Скопировать адрес', DONE: '✓ Скопировано', CLOSE: 'Закрыть' },
  DETAIL: { BACK: 'Назад', BACK_CAREER: 'Назад к карьере', BACK_ACH: 'Назад к достижениям', NOT_FOUND: 'не найден', KEY_METRICS: 'Ключевые метрики', FEATURES: 'Возможности', TECH_STACK: 'Технологии', KEY_ACH: 'Ключевые достижения', TYPE_PROJECT: 'Проект', TYPE_CAREER: 'Карьера', TYPE_ACH: 'Достижение' },
};

const PONYTAIL = Object.freeze({
  SCRUB: 1, DURATION: 600, EASE: 'power2.inOut',
  CATEGORIES,
  LOCALE: { EN, RU },
  SCENES: [
    { id: 'intro', range: [0, 0.18], label: { EN: '15 Years in Code', RU: '15 лет в коде' }, camera: { position: { from: [0, 0, 22], to: [0, 0, 10] }, fov: { from: 60, to: 46 } }, geometry: { type: 'particleLines', particleCount: 10000, spread: 16, assembleSpeed: 0.6 }, postFX: { bloom: { threshold: 0.5, strength: 1.4, radius: 0.5 }, motionBlur: false }, ambient: { gain: 0.5 } },
    { id: 'chronicle', range: [0.18, 0.35], label: { EN: 'Career Timeline', RU: 'Карьерный путь' }, camera: { position: { from: [0, 0, 10], to: [2, -0.5, 7] }, fov: { from: 46, to: 42 } }, geometry: { type: 'timelineMesh', segments: 15, uiEvolution: true }, postFX: { bloom: { threshold: 0.4, strength: 0.9, radius: 0.35 }, motionBlur: false }, ambient: { gain: 0.45 } },
    { id: 'projects', range: [0.35, 0.62], label: { EN: 'Projects & Impact', RU: 'Проекты и влияние' }, camera: { position: { from: [2, -0.5, 7], to: [0, 0.2, 4.5] }, fov: { from: 42, to: 36 } }, geometry: { type: 'graph3d', nodes: [
      { id: 'go', label: 'Go', group: 'backend', size: 3, color: 0x00add8 },
      { id: 'rust', label: 'Rust', group: 'backend', size: 2.5, color: 0xdea584 },
      { id: 'python', label: 'Python', group: 'backend', size: 3, color: 0xffd43b },
      { id: 'ts', label: 'TypeScript', group: 'lang', size: 2.5, color: 0x3178c6 },
      { id: 'k8s', label: 'Kubernetes', group: 'infra', size: 3, color: 0x326ce5 },
      { id: 'kafka', label: 'Kafka', group: 'infra', size: 2.5, color: 0x231f20 },
      { id: 'postgres', label: 'PostgreSQL', group: 'data', size: 2.5, color: 0x336791 },
      { id: 'redis', label: 'Redis', group: 'data', size: 2, color: 0xdc382d },
      { id: 'pytorch', label: 'PyTorch', group: 'ml', size: 2.5, color: 0xee4c2c },
      { id: 'aws', label: 'AWS', group: 'infra', size: 2.5, color: 0xff9900 },
      { id: 'solidity', label: 'Solidity', group: 'blockchain', size: 2, color: 0x888888 },
      { id: 'react', label: 'React', group: 'frontend', size: 2.5, color: 0x61dafb },
      { id: 'temporal', label: 'Temporal', group: 'infra', size: 2, color: 0x4b7bec },
      { id: 'clickhouse', label: 'ClickHouse', group: 'data', size: 2, color: 0xf0c040 },
      { id: 'flink', label: 'Flink', group: 'infra', size: 2, color: 0x0096d6 },
    ], edges: [
      ['go', 'temporal'], ['go', 'kafka'], ['go', 'postgres'], ['go', 'k8s'],
      ['rust', 'kafka'], ['rust', 'clickhouse'],
      ['python', 'pytorch'], ['python', 'aws'], ['python', 'flink'],
      ['ts', 'react'], ['ts', 'solidity'],
      ['k8s', 'aws'], ['k8s', 'temporal'],
      ['postgres', 'redis'], ['kafka', 'flink'],
      ['pytorch', 'aws'], ['solidity', 'ts'],
    ], cameraPath: 'flythrough' }, postFX: { bloom: { threshold: 0.25, strength: 1.6, radius: 0.55 }, motionBlur: { strength: 0.25 } }, ambient: { gain: 0.5 } },
    { id: 'achievements', range: [0.62, 0.80], label: { EN: 'Milestones', RU: 'Достижения' }, camera: { position: { from: [0, 0.2, 4.5], to: [0.5, 0, 3.8] }, fov: { from: 36, to: 32 } }, geometry: { type: 'achievementNodes' }, postFX: { bloom: { threshold: 0.2, strength: 1.9, radius: 0.5 }, motionBlur: false }, ambient: { gain: 0.35 } },
    { id: 'cta', range: [0.80, 1.0], label: { EN: 'Initiate Consult', RU: 'Начать консультацию' }, camera: { position: { from: [0.5, 0, 3.8], to: [0, 0, 2.5] }, fov: { from: 32, to: 28 } }, geometry: { type: 'terminalUI', terminalLines: 12, scanlineEffect: true, glowIntensity: { from: 1.0, to: 1.6 } }, postFX: { bloom: { threshold: 0.15, strength: 2.2, radius: 0.6 }, motionBlur: false }, ambient: { gain: 0.2, fadeOut: true } },
  ],
  SEO: {
    EN: { title: 'Aleksandr Gribakin — Lead Engineer | 15 Years Building at Scale', description: 'Lead Full Stack Engineer with 15 years architecting fintech systems processing $4B+, ML fraud engines at 8K TPS, distributed systems serving 12M+ users. Go, Rust, Python, TS.', keywords: 'lead full stack engineer, system architect, fintech, distributed systems, Go, Rust, Python, Kubernetes' },
    RU: { title: 'Александр Грибакин — Lead Engineer | 15 лет создания масштабных систем', description: 'Lead Full Stack Engineer с 15-летним опытом: fintech $4B+, ML фрод-детекция 8K TPS, распределенные системы для 12M+ пользователей. Go, Rust, Python, TS.', keywords: 'lead full stack engineer, системный архитектор, fintech, распределенные системы, Go, Rust, Python' },
    structuredData: {
      '@context': 'https://schema.org', '@type': 'Person', name: 'Aleksandr Gribakin', givenName: 'Aleksandr', familyName: 'Gribakin',
      email: 'RF24KRSK@gmail.com', url: 'https://dev24.pro',
      knowsAbout: ['Distributed Systems', 'Fintech', 'System Architecture', 'ML/AI', 'Go', 'Rust', 'Python', 'Kubernetes', 'Microservices', 'Event-Driven Architecture'],
      sameAs: ['https://github.com/RF24KRSK', 'https://linkedin.com/in/aleksandr-gribakin'],
    },
  },
});

export default PONYTAIL;
