const CATEGORIES = ['Infrastructure', 'CI/CD', 'Backend', 'Data', 'Frontend', 'Observability'];

const EN = {
  NAME: 'ALEKSANDR GRIBAKIN', TAGLINE: '15 Years in Code', SKIP_LINK: 'Skip to content',
  ROLE: 'Lead Full Stack & DevOps Engineer',
  INTRO_SUB: 'Building systems that scale. Automating what should never have been manual.',
  // "Projects & Impact" promised delivered jobs and delivered a method, which
  // is what made the section read as empty. The two are now named apart.
  SECTION_TITLES: {
    STACK: 'Toolbox',
    STACK_BACKED: 'Used in the work described on this page',
    STACK_BACKED_TITLE: '{n} of them appear in the work described above — most often these:',
    STACK_ALL: 'All',
    STACK_SUB: '{n} tools across fifteen areas — what I can pick up. Use the filter to see one layer of it at a time.',
    STATS: 'The Work in Numbers',
    CAREER: 'Career Timeline',
    PROJECTS: 'Reference Architectures',
    PROJECTS_SUB: 'How I approach these kinds of problems — the method, not a client list',
    PRODUCTS: 'Current Projects',
    PRODUCTS_SUB: 'My own products — open them and look, no NDA in the way',
    WEB: 'Client Projects',
    WEB_SUB: 'Commercial sites, and exactly which part of them was mine',
    PROCESS: 'How I Work',
    PROCESS_SUB: 'Six things worth knowing before we start — hours, estimates, handover and what happens after',
    ACHIEVEMENTS: 'Professional Milestones',
    ACHIEVEMENTS_SUB: 'Six shifts the industry has since packaged and sells ready-made. I worked through them before anything was ready-made.',
  },
  FOOTER: {
    HOURS: 'Working hours',
    WRITE: 'Write to me',
    PRIVACY: 'Privacy policy',
    RIGHTS: 'All rights reserved',
  },
  // Unlike the client cases, these link out: they are his to show.
  PRODUCT_LABELS: {
    ROLE: 'Role', SINCE: 'Live since', STACK: 'Built with', OPEN: 'Open the site',
    MORE: 'What it does',
  },
  WEB_LABELS: {
    // No "open the site" link: the clients are named, not linked to.
    ROLE: 'Role', PERIOD: 'Period', STACK: 'Stack',
    SITUATION: 'Situation', WORK: 'What was done', OUTCOME: 'What changed', EVIDENCE: 'Evidence',
    SCOPE: 'What was built', COMPLEXITY: 'Why it was hard', RESULTS: 'In numbers',
    BEFORE: 'before', AFTER: 'after', RESULT: 'result',
    UNNAMED: 'Client not named at their request',
  },
  // Headline numbers are computed in src/lib/stats.js from the content below —
  // only their wording lives here, so a figure can never contradict the data.
  STATS_LABELS: {
    // Every hint below carries money, time or risk. A number that cannot be
    // given such a sentence does not belong in this row — which is why the
    // "85 capabilities shipped" tile is gone.
    EXPERIENCE: 'Years in Production',
    EXPERIENCE_HINT: 'In production since {year} — migrating systems that were not allowed to stop',
    PROJECTS: 'Reference Architectures',
    PROJECTS_HINT: 'Proven approaches across {n} disciplines — the method, not a client list',
    STACK: 'Technologies in Production',
    STACK_HINT: 'Front end, back end and infrastructure from one contractor instead of three. Most used: {top}',
    AVAILABILITY: 'Availability Target',
    AVAILABILITY_HINT: 'That is at most {mins} min of downtime a month',
    AVAILABILITY_HINT_NONE: 'No availability figure is tracked yet',
    MILESTONES: 'Professional Milestones', MILESTONES_HINT: 'From {from} to {to} — each one a turning point, not a solution',
    UNIT_YEARS: 'yrs', UNIT_PROJECTS: 'projects',
    EXPAND: 'Show breakdown', COLLAPSE: 'Hide breakdown',
  },
  METRIC: {
    HIGHER_BETTER: 'higher is better', LOWER_BETTER: 'lower is better',
    RANK: 'rank {r} of {n} in this portfolio', OF_TARGET: 'of 100%',
    SCALE_NOTE: 'Bar length shows how this value sits against every comparable metric across all projects.',
  },
  TERMINAL: {
    ACCESS: 'ACCESS GRANTED',
    BOOT_CLIENT: 'Client', BOOT_SESSION: 'Session', BOOT_TARGET: 'Target', BOOT_SHELL: 'Shell',
    WELCOME: 'Type `help` to see what this thing does.',
    HEAD_HELP: 'AVAILABLE COMMANDS', HEAD_ID: 'IDENTITY', HEAD_ABOUT: 'ABOUT',
    HEAD_STATS: 'SYSTEM PROFILE', HEAD_CAREER: 'CAREER LOG', HEAD_TARGETS: 'TARGETS',
    HEAD_WEB: 'CLIENT PROJECTS', HINT_WEB: 'web <id> for the case',
    HEAD_LIVE: 'CURRENT PROJECTS', LIVE_EMPTY: 'Nothing published yet.',
    HEAD_PROCESS: 'HOW I WORK', HEAD_LEGAL: 'LEGAL & PRIVACY',
    HINT_LEGAL: 'legal — terms and privacy policy',
    LABEL_EMAIL: 'Email', LABEL_TG: 'Telegram', LABEL_HOURS: 'Hours', LABEL_REPLY: 'Reply',
    WEB_EMPTY: 'No client cases published yet.',
    HEAD_STACK: 'TECHNOLOGY', HEAD_TOOLS: 'TOOLBOX', HINT_TOOLS: 'tools <group> for one area', HEAD_MILESTONES: 'MILESTONES', HEAD_TRANSMIT: 'TRANSMIT',
    HEAD_METRICS: 'KEY METRICS', HEAD_FEATURES: 'FEATURES',
    CMD: {
      HELP: 'this list', WHOAMI: 'who you are talking to', ABOUT: 'the short version',
      STATS: 'headline numbers, computed from the content', CAREER: 'career log, or one entry in full',
      PROJECTS: 'list the reference architectures', OPEN: 'full brief on one of them',
      WEB: 'client sites, and one case in full',
      LIVE: 'my own products, running now',
      PROCESS_CMD: 'how I work: hours, estimates, handover',
      LEGAL_CMD: 'terms, invoicing and the privacy policy',
    STACK: 'technology, by how often it appears', TOOLS: 'the whole toolbox, by area', ACH: 'milestones, or one in full',
      CONTACT: 'send a message from here', LANG: 'switch language', MODE: 'leave for another interface',
      NEOFETCH: 'the obligatory one', COFFEE: 'buy me one', HISTORY: 'what you have typed',
      CLEAR: 'wipe the screen', EXIT: 'back to the standard view',
    },
    HINT_KEYS: 'Tab completes · ↑ ↓ history · Ctrl+L clears · Ctrl+C aborts',
    HINT_BREAKDOWN: 'Run `stats --breakdown` for the charts.',
    HINT_DETAIL: 'career {n} for the full entry',
    HINT_DETAIL_N: 'achievements {n}',
    HINT_OPEN: 'open <id> for the full brief',
    HINT_LS: 'Run `projects` to list them.',
    HINT_HELP: 'Type `help` for the list.',
    NOT_FOUND: 'command not found: {c}',
    NO_ENTRY: 'No entry {n}.', NO_CAT: 'No category matching "{c}".', NO_TARGET: 'No target "{id}".',
    USAGE_OPEN: 'usage: open <project-id>',
    LBL_STACK: 'Stack', LBL_CAT: 'Category', LBL_ACCESS: 'Access',
    LANG_CURRENT: 'Language: {l}. Usage: lang <en|ru>', LANG_SET: 'Language set to {l}.',
    MODE_USAGE: 'usage: mode <business|desktop>', MODE_SET: 'Switching to {m}…',
    TRANSMIT_INTRO: 'Direct line. Three questions, then it sends.',
    TRANSMIT_CANCEL: 'Ctrl+C to abort.', TRANSMIT_PROMPT: 'transmit>', TRANSMIT_ABORTED: '^C aborted.',
    ASK_NAME: 'Your name?', ASK_EMAIL: 'Email to reply to?', ASK_MESSAGE: 'What are you building?',
    SENDING: 'Transmitting…', SENT: 'TRANSMISSION SENT (200 OK)',
    SEND_FAIL: 'TRANSMISSION FAILED ({e})', SEND_FALLBACK: 'Mail directly: {mail}',
    SUDO: 'visitor is not in the sudoers file. This incident has been reported.',
    NO_HISTORY: 'No history yet.',
    EXIT: 'Session closed. Returning to the standard view…',
  },
  CAREER: [
    { period: '2022–2026', role: 'Senior DevOps / Platform Engineer', company: 'Cloud-native platform', desc: 'Ran the Kubernetes platform product teams build on: a namespace arrives with quotas, ingress, TLS and monitoring already wired together, so shipping a service does not require learning the cluster. Delivery moved to GitOps — the repository holds the desired state, and anything changed by hand on the cluster is reverted automatically. The last physical servers went into hybrid cloud; maintenance spend fell 30–40%.' },
    { period: '2019–2022', role: 'DevOps Engineer', company: 'Microservices migration', desc: 'Dozens of microservices, each with a hand-built pipeline that had long since drifted from its neighbours. Reduced them to one template: a service declares its type and gets build, tests and deployment already assembled. Releasing stopped being a coordinated multi-day event — about fifteen minutes now, with no downtime.' },
    { period: '2016–2019', role: 'Full Stack Engineer', company: 'SaaS product', desc: 'One product end to end: backend, frontend and the infrastructure under both. Most of the work was the database under growing load — replication to spread reads, sharding to spread writes, and caching in tiers with explicit rules about which data is allowed to go stale. Most of the gain came from reading query plans rather than from buying hardware.' },
    { period: '2013–2016', role: 'Full Stack Developer', company: 'Web platform', desc: 'A monolith on classic virtualisation, released by hand against a checklist. Wrote the first deployment scripts and moved environment configuration out of people’s heads and into the repository — the ancestor of what later got called CI/CD. This is where it became clear that a manual step in a release is not saved effort, it is a deferred incident.' },
    { period: '2011–2013', role: 'Web Developer', company: 'Digital agency', desc: 'LAMP on physical servers: PHP and MySQL, Apache and nginx tuned by hand, logs and crashes read the same way. An agency with no dedicated sysadmins — whoever wrote the site kept it running after handover. That is where the habit of looking at an application together with the machine it lives on comes from.' },
  ],
  CATEGORIES: ['All', ...CATEGORIES],
  // Display names only — the keys above are what `cat` matches on. "Storage &
  // search" rather than "Data & storage" so the filter and the toolbox area it
  // corresponds to ("Storage, cache, search") are recognisably the same subject
  // to someone who scrolls from one to the other.
  CATEGORY_LABELS: ['All', 'Infrastructure & Cloud', 'CI/CD & Automation', 'Backend', 'Storage & Search', 'Frontend', 'Observability'],
  PROJECTS: [
    // --- Infrastructure (4) ---
    { id: 'bare-to-cloud', name: 'Bare-Metal to Hybrid Cloud', cat: 'Infrastructure', tag: 'Migration', stack: 'Terraform, Ansible, AWS, GCP, Linux', desc: 'Moving off servers you own and pay for whether or not they are busy. Done in stages — take stock, match the new setup to the old, then move traffic — so the business never rides on one big switchover night.', metric: '30-40% cost cut / staged cutover' },
    { id: 'k8s-platform', name: 'Kubernetes Platform', cat: 'Infrastructure', tag: 'Platform', stack: 'Kubernetes, Helm, ArgoCD, Terraform, Prometheus', desc: 'Shared infrastructure your developers can use without first becoming infrastructure specialists. They ask for space and get it already set up, so new work starts the same day instead of waiting on someone else.', metric: '99.9% uptime / self-serve namespaces' },
    { id: 'iac-baseline', name: 'Infrastructure as Code Baseline', cat: 'Infrastructure', tag: 'IaC', stack: 'Terraform, Ansible, GitLab CI, Vault, Linux', desc: 'Every server described in a file, so any of them can be rebuilt from nothing in minutes. Nothing depends on one machine nobody dares touch, or on what somebody changed by hand two years ago and did not write down.', metric: '100% reproducible / 3 environments' },
    { id: 'env-parity', name: 'Local and Production Parity', cat: 'Infrastructure', tag: 'Tooling', stack: 'Docker, Docker Compose, Terraform, Make, Linux', desc: 'A developer\u2019s laptop, the test system and the live one all run the same thing. That removes an entire category of delay: bugs that appear only after release, which nobody can reproduce and everybody has to guess at.', metric: 'One image / 4 environments' },
    // --- CI/CD (3) ---
    { id: 'pipeline-standard', name: 'Standardised Delivery Pipelines', cat: 'CI/CD', tag: 'Delivery', stack: 'GitLab CI, Jenkins, Docker, Helm, GitHub Actions', desc: 'One release process shared by every part of the system, instead of each team maintaining its own. Shipping a change goes from a planned multi-day operation to about fifteen minutes.', metric: '15 min release / dozens of services' },
    { id: 'zero-downtime', name: 'Zero-Downtime Deployment', cat: 'CI/CD', tag: 'Deployment', stack: 'Kubernetes, ArgoCD, NGINX, Helm, Prometheus', desc: 'Updates go out without taking the service down, and a release that starts misbehaving is pulled back automatically before most customers see anything. No more maintenance windows announced in advance.', metric: 'Zero downtime / 90s rollback' },
    { id: 'gitops', name: 'GitOps Delivery Model', cat: 'CI/CD', tag: 'GitOps', stack: 'ArgoCD, Git, Helm, Kustomize, Kubernetes', desc: 'One written record of how the system is supposed to be set up, and the system corrects itself back to it. Changes made by hand at three in the morning do not survive to become next month\u2019s mystery.', metric: 'Git as source of truth / auto-reconcile' },
    // --- Backend (3) ---
    { id: 'monolith-split', name: 'Monolith to Services', cat: 'Backend', tag: 'Architecture', stack: 'PHP, Symfony, Go, gRPC, RabbitMQ', desc: 'Splitting one large aging system into parts that can be worked on separately — while it stays open for business the whole time. No freeze, and no rewrite-from-scratch project that runs two years and delivers nothing.', metric: 'Incremental cutover / no freeze' },
    { id: 'api-layer', name: 'API Layer and Contracts', cat: 'Backend', tag: 'API', stack: 'Node.js, TypeScript, OpenAPI, gRPC, NGINX', desc: 'A written agreement about how the parts of your system talk to each other, generated from one source. When someone changes something incompatible, it fails on their screen during development rather than for a customer.', metric: 'Generated clients / versioned contracts' },
    { id: 'async-jobs', name: 'Async Job Processing', cat: 'Backend', tag: 'Queues', stack: 'Python, FastAPI, Celery, RabbitMQ, Redis', desc: 'Slow work — reports, imports, emails, payment callbacks — moved out of the customer\u2019s way so pages stay fast. Anything that fails is retried safely and, if it keeps failing, lands somewhere a person actually looks.', metric: 'Idempotent retries / DLQ triage' },
    // --- Data (3) ---
    { id: 'pg-highload', name: 'PostgreSQL Under Load', cat: 'Data', tag: 'Database', stack: 'PostgreSQL, PgBouncer, Patroni, Prometheus, Linux', desc: 'Making the database keep up as the data grows, usually by finding out what it is actually doing rather than by buying a bigger machine. Cheaper than hardware, and it lasts longer.', metric: 'Read scale-out / partitioned writes' },
    { id: 'cache-tiers', name: 'Multi-Level Caching', cat: 'Data', tag: 'Caching', stack: 'Redis, NGINX, CDN, Node.js, PostgreSQL', desc: 'Keeping ready-made answers close to the visitor so pages load fast and the servers do less work. Each layer has an explicit rule for how stale it may be, so nobody is ever shown an old price.', metric: '4 tiers / explicit invalidation' },
    { id: 'search-stack', name: 'Search and Document Store', cat: 'Data', tag: 'Search', stack: 'Elasticsearch, MongoDB, Python, Kafka, Redis', desc: 'Search that finds things by meaning rather than exact wording, and stays current as the catalogue changes. Rebuilding the index happens while the site is open, not overnight with the service down.', metric: 'Live reindex / change-stream fed' },
    // --- Frontend (2) ---
    { id: 'spa-ssr', name: 'SPA with Server-Side Rendering', cat: 'Frontend', tag: 'Web', stack: 'React, TypeScript, Vite, Node.js, NGINX', desc: 'Pages arrive already drawn, so visitors see content immediately and search engines can read it — then behave like an app once loaded. Fixes the common problem of a site that ranks badly because it is empty until scripts run.', metric: 'SSR first paint / typed end to end' },
    { id: 'ui-kit', name: 'Component Library', cat: 'Frontend', tag: 'Design System', stack: 'Vue.js, TypeScript, Webpack, Storybook, CSS', desc: 'One set of buttons, forms and layouts that every page is built from. New screens get assembled instead of drawn from scratch, they look consistent by default, and people using screen readers are not an afterthought.', metric: '40+ components / WCAG AA' },
    // --- Observability (2) ---
    { id: 'observability', name: 'Observability Stack', cat: 'Observability', tag: 'Monitoring', stack: 'Prometheus, Grafana, Loki, Elasticsearch, Alertmanager', desc: 'Knowing what the system is doing, and being able to follow one customer\u2019s request all the way through when something goes wrong. The difference between "the site feels slow" and knowing which step is slow, and why.', metric: 'Correlated signals / SLO-based alerts' },
    { id: 'incident', name: 'Incident Response', cat: 'Observability', tag: 'Process', stack: 'Grafana, Alertmanager, Ansible, Git, Linux', desc: 'A clear answer to who is woken up when something breaks at night, written instructions that match reality, and a review afterwards that produces a fix rather than a culprit.', metric: 'Owned rotations / current runbooks' },
  ],
  // Milestones describe work inside employers, not public records. Nothing here
  // claims a patent, a conference programme slot, a journal byline or a
  // repository star count — those are all externally verifiable, and inventing
  // one is forgery rather than a CV claim.
  ACHIEVEMENTS: [
    { year: '2024', title: 'The Last Physical Server', desc: 'The final rack went dark. The long part was the inventory, not the move: no complete list of what ran on that hardware existed outside three people’s heads.' },
    { year: '2022', title: 'Releases Stopped Being Events', desc: 'Deployment went from a multi-day operation to roughly fifteen minutes with no downtime. When releasing is cheap, people stop saving changes up for it.' },
    { year: '2020', title: 'The End of Oral Tradition', desc: 'Environments stopped being unique. A difference between development, staging and production became a defect rather than a fact of life.' },
    { year: '2018', title: 'It Is Rarely the Database', desc: 'A year on storage under load: the bottleneck is almost never the engine, it is the shape of the questions asked of it.' },
    { year: '2016', title: 'DevOps When It Was Two Departments', desc: 'Development and operations had different targets and different definitions of done. An incident is almost never purely technical.' },
    { year: '2011', title: 'First Production Commit', desc: 'PHP on a physical server, deployed over FTP. It worked. Almost — and everything above is an answer to why almost is not enough.' },
  ],
  CTA_TITLE: 'Initiate Consult',
  CTA_SUB: 'Ready to build something extraordinary? One message starts the conversation.',
  FORM: { NAME: 'Your Name', EMAIL: 'Email Address', MESSAGE: 'Describe your project...', SUBMIT: 'Initiate Consult', SUCCESS: '▸ Message transmitted. I will reach out shortly.', PLACEHOLDER_NAME: 'Your name, or your best alias', PLACEHOLDER_EMAIL: 'where pixels meet purpose', PLACEHOLDER_MSG: 'Product, team, dream — paint the picture...', CONSENT: 'I agree to my details being processed as described in the', CONSENT_LINK: 'privacy policy', CONSENT_ASK: 'Agree to the privacy policy? (y/n)' },
  FORM_ERRORS: {
    CONSENT_REQUIRED: 'Please agree to the privacy policy',
    NAME_REQUIRED: 'Enter your name',
    NAME_MIN: 'Name must be at least 2 characters',
    NAME_MAX: 'Name is too long',
    NAME_PATTERN: 'Name contains invalid characters',
    EMAIL_REQUIRED: 'Enter your email',
    EMAIL_INVALID: 'That does not look like an email',
    EMAIL_PATTERN: 'That does not look like an email',
    MSG_REQUIRED: 'Describe your project briefly',
    MSG_MIN: 'Message must be at least 10 characters',
    MSG_MAX: 'Message is too long (max 2000)',
    NETWORK: 'Network error. Try again later.',
    RATE_LIMIT: 'Slow down. One message at a time.',
    DELIVERY_DOWN: 'Could not send from here. Please write to {mail} directly.',
  },
  _PAGE_404: {
    TITLE: '404 — Page Not Found',
    SUB: 'This route does not exist.',
    CTA: 'Return Home',
  },
  BIO: 'Fifteen years building and scaling distributed systems, across the industry\'s move from bare-metal servers and monoliths to cloud-native, Kubernetes and GitOps. I take on the work teams postpone: paying down technical debt, building deployment from nothing, and keeping systems running.',
  STATS_DESC: 'Infrastructure migration, delivery automation and database performance under load.',
  ABOUT: 'About', CAREER_TITLE: 'Career', PROJECTS_TITLE: 'Projects', ACHIEVEMENTS_TITLE: 'Achievements', SETTINGS: 'Settings', SETTINGS_LANG: 'Language', SETTINGS_THEME: 'Theme', SETTINGS_THEME_HINT: '(Business mode only)', SETTINGS_INTERFACE: 'Interface', SETTINGS_CLOSE: 'Close', MAIL: 'Mail', THEME_DARK: 'Dark', THEME_LIGHT: 'Light', MODE_BUSINESS: 'Business', MODE_DESKTOP: 'Desktop', MODE_TERMINAL: 'Terminal',
  COFFEE: { TITLE: '☕ Buy me a coffee', NETWORK: 'USDT TRC-20', COPY: 'Copy Address', DONE: '✓ Copied', CLOSE: 'Close' },
  DETAIL: { BACK: 'Back', BACK_CAREER: 'Back to Career', BACK_ACH: 'Back to Achievements', NOT_FOUND: 'not found', KEY_METRICS: 'Key Metrics', FEATURES: 'Features', TECH_STACK: 'Tech Stack', KEY_ACH: 'Key Achievements', TYPE_PROJECT: 'Project', TYPE_CAREER: 'Career', TYPE_ACH: 'Achievement', PRIVATE_REPO: 'Private repository', OPEN_DETAIL: 'Open', REFERENCE_NOTE: 'Reference architecture. Client code is under NDA, so this page describes the design and the reasoning behind it rather than a specific deployment.' },
};

const RU = {
  NAME: 'АЛЕКСАНДР ГРИБАКИН', TAGLINE: '15 лет в коде', SKIP_LINK: 'Перейти к содержанию',
  ROLE: 'Lead Full Stack & DevOps Engineer',
  INTRO_SUB: 'Строю системы, которые масштабируются. Автоматизирую то, что никогда не должно было делаться руками.',
  SECTION_TITLES: {
    STACK: 'Инструментарий',
    STACK_BACKED: 'Встречается в описанных на этой странице работах',
    STACK_BACKED_TITLE: 'Из них {n} встречаются в описанных выше работах — чаще всего эти:',
    STACK_ALL: 'Все',
    STACK_SUB: '{n} инструментов в пятнадцати областях — то, за что я могу взяться. Фильтр показывает по одному слою за раз.',
    STATS: 'Результаты в цифрах',
    CAREER: 'Карьерный путь',
    PROJECTS: 'Отработанные архитектуры',
    PROJECTS_SUB: 'Как я решаю эти классы задач — метод, а не список заказчиков',
    PRODUCTS: 'Текущие проекты',
    PRODUCTS_SUB: 'Мои собственные продукты — можно открыть и посмотреть, без NDA',
    WEB: 'Клиентские проекты',
    WEB_SUB: 'Коммерческие сайты и то, какая именно часть в них моя',
    PROCESS: 'Как я работаю',
    PROCESS_SUB: 'Шесть вещей, которые стоит знать до начала: часы, оценка, сдача и что будет после',
    ACHIEVEMENTS: 'Профессиональные вехи',
    ACHIEVEMENTS_SUB: 'Шесть переходов, которые сегодня продают готовыми решениями. Я проходил их, когда готовых решений не существовало.',
  },
  FOOTER: {
    HOURS: 'Рабочий график',
    WRITE: 'Написать',
    PRIVACY: 'Политика конфиденциальности',
    RIGHTS: 'Все права защищены',
  },
  PRODUCT_LABELS: {
    ROLE: 'Роль', SINCE: 'Работает с', STACK: 'На чём', OPEN: 'Открыть сайт',
    MORE: 'Подробнее',
  },
  WEB_LABELS: {
    ROLE: 'Роль', PERIOD: 'Период', STACK: 'Стек',
    SITUATION: 'Ситуация', WORK: 'Что сделано', OUTCOME: 'Что изменилось', EVIDENCE: 'Чем подтверждается',
    SCOPE: 'Что построено', COMPLEXITY: 'В чём была сложность', RESULTS: 'В цифрах',
    BEFORE: 'было', AFTER: 'стало', RESULT: 'итог',
    UNNAMED: 'Заказчик не называется по его просьбе',
  },
  STATS_LABELS: {
    EXPERIENCE: 'Лет в продакшене',
    EXPERIENCE_HINT: 'В продакшене с {year} года — мигрировал то, что нельзя было останавливать',
    PROJECTS: 'Отработанных архитектур',
    PROJECTS_HINT: 'Решения, доведённые до продакшена, в {n} направлениях — это метод, а не список заказчиков',
    STACK: 'Технологий в работе',
    STACK_HINT: 'Фронт, бэк и инфраструктура — один подрядчик вместо трёх. Чаще всего: {top}',
    AVAILABILITY: 'Целевая доступность',
    AVAILABILITY_HINT: 'Это не больше {mins} мин простоя в месяц',
    AVAILABILITY_HINT_NONE: 'Показатель доступности пока не отслеживается',
    MILESTONES: 'Профессиональных вех', MILESTONES_HINT: 'С {from} по {to} — каждая про перелом, а не про решение',
    UNIT_YEARS: 'лет', UNIT_PROJECTS: 'проектов',
    EXPAND: 'Показать разбивку', COLLAPSE: 'Скрыть разбивку',
  },
  METRIC: {
    HIGHER_BETTER: 'больше — лучше', LOWER_BETTER: 'меньше — лучше',
    RANK: 'место {r} из {n} в портфолио', OF_TARGET: 'из 100%',
    SCALE_NOTE: 'Длина полосы показывает, как значение выглядит на фоне всех сопоставимых метрик по всем проектам.',
  },
  TERMINAL: {
    ACCESS: 'ДОСТУП РАЗРЕШЁН',
    BOOT_CLIENT: 'Клиент', BOOT_SESSION: 'Сессия', BOOT_TARGET: 'Цель', BOOT_SHELL: 'Оболочка',
    WELCOME: 'Введите `help`, чтобы узнать, что тут умеют.',
    HEAD_HELP: 'ДОСТУПНЫЕ КОМАНДЫ', HEAD_ID: 'ЛИЧНОСТЬ', HEAD_ABOUT: 'О СЕБЕ',
    HEAD_STATS: 'ПРОФИЛЬ СИСТЕМЫ', HEAD_CAREER: 'ЖУРНАЛ КАРЬЕРЫ', HEAD_TARGETS: 'ЦЕЛИ',
    HEAD_LIVE: 'ТЕКУЩИЕ ПРОЕКТЫ', LIVE_EMPTY: 'Пока ничего не опубликовано.',
    HEAD_WEB: 'КЛИЕНТСКИЕ ПРОЕКТЫ', HINT_WEB: 'web <id> — кейс целиком',
    HEAD_PROCESS: 'КАК Я РАБОТАЮ', HEAD_LEGAL: 'ЮРИДИЧЕСКОЕ И ПРИВАТНОСТЬ',
    HINT_LEGAL: 'legal — условия и политика конфиденциальности',
    LABEL_EMAIL: 'Почта', LABEL_TG: 'Telegram', LABEL_HOURS: 'График', LABEL_REPLY: 'Ответ',
    WEB_EMPTY: 'Клиентские кейсы пока не опубликованы.',
    HEAD_STACK: 'ТЕХНОЛОГИИ', HEAD_TOOLS: 'ИНСТРУМЕНТЫ', HINT_TOOLS: 'tools <группа> — одна область', HEAD_MILESTONES: 'ВЕХИ', HEAD_TRANSMIT: 'ПЕРЕДАЧА',
    HEAD_METRICS: 'КЛЮЧЕВЫЕ МЕТРИКИ', HEAD_FEATURES: 'ВОЗМОЖНОСТИ',
    CMD: {
      HELP: 'этот список', WHOAMI: 'с кем вы говорите', ABOUT: 'коротко о главном',
      STATS: 'цифры, вычисленные из контента', CAREER: 'журнал карьеры или одна запись целиком',
      PROJECTS: 'список референсных архитектур', OPEN: 'полная справка по одной из них',
      WEB: 'клиентские сайты и один кейс целиком',
      LIVE: 'мои собственные продукты, работают сейчас',
      PROCESS_CMD: 'как я работаю: часы, оценка, сдача',
      LEGAL_CMD: 'условия, инвойсы и политика конфиденциальности',
    STACK: 'технологии по частоте появления', TOOLS: 'весь инструментарий по областям', ACH: 'вехи или одна целиком',
      CONTACT: 'отправить сообщение прямо отсюда', LANG: 'сменить язык', MODE: 'уйти в другой интерфейс',
      NEOFETCH: 'та самая команда', COFFEE: 'угостить кофе', HISTORY: 'что вы вводили',
      CLEAR: 'очистить экран', EXIT: 'вернуться к обычному виду',
    },
    HINT_KEYS: 'Tab дополняет · ↑ ↓ история · Ctrl+L очищает · Ctrl+C прерывает',
    HINT_BREAKDOWN: 'Введите `stats --breakdown` для графиков.',
    HINT_DETAIL: 'career {n} — запись целиком',
    HINT_DETAIL_N: 'achievements {n}',
    HINT_OPEN: 'open <id> — полная справка',
    HINT_LS: 'Введите `projects`, чтобы увидеть список.',
    HINT_HELP: 'Введите `help` для списка.',
    NOT_FOUND: 'команда не найдена: {c}',
    NO_ENTRY: 'Записи {n} нет.', NO_CAT: 'Категория "{c}" не найдена.', NO_TARGET: 'Цель "{id}" не найдена.',
    USAGE_OPEN: 'использование: open <project-id>',
    LBL_STACK: 'Стек', LBL_CAT: 'Категория', LBL_ACCESS: 'Доступ',
    LANG_CURRENT: 'Язык: {l}. Использование: lang <en|ru>', LANG_SET: 'Язык переключён на {l}.',
    MODE_USAGE: 'использование: mode <business|desktop>', MODE_SET: 'Переключаюсь на {m}…',
    TRANSMIT_INTRO: 'Прямая линия. Три вопроса — и уходит.',
    TRANSMIT_CANCEL: 'Ctrl+C — прервать.', TRANSMIT_PROMPT: 'transmit>', TRANSMIT_ABORTED: '^C прервано.',
    ASK_NAME: 'Как вас зовут?', ASK_EMAIL: 'На какой email отвечать?', ASK_MESSAGE: 'Что вы строите?',
    SENDING: 'Передаю…', SENT: 'СООБЩЕНИЕ ОТПРАВЛЕНО (200 OK)',
    SEND_FAIL: 'ПЕРЕДАЧА НЕ УДАЛАСЬ ({e})', SEND_FALLBACK: 'Написать напрямую: {mail}',
    SUDO: 'visitor отсутствует в файле sudoers. Инцидент запротоколирован.',
    NO_HISTORY: 'История пуста.',
    EXIT: 'Сессия закрыта. Возвращаюсь к обычному виду…',
  },
  CAREER: [
    { period: '2022–2026', role: 'Senior DevOps / Platform Engineer', company: 'Cloud-native платформа', desc: 'Вёл Kubernetes-платформу, на которой работают продуктовые команды: неймспейс выдаётся сразу с квотами, ingress, TLS и мониторингом, и чтобы выкатить сервис, разбираться в устройстве кластера не нужно. Поставку перевёл на GitOps: нужное состояние описано в репозитории, а правки руками на кластере откатываются автоматически. Последние физические серверы ушли в гибридное облако, обслуживание подешевело на 30–40%.' },
    { period: '2019–2022', role: 'DevOps Engineer', company: 'Миграция на микросервисы', desc: 'Десятки микросервисов, у каждого свой самописный пайплайн, давно разошедшийся с соседними. Свёл их к одному шаблону: сервис объявляет свой тип и получает готовую сборку, тесты и выкатку. Релиз перестал быть согласованным событием на несколько дней — теперь это около пятнадцати минут и без простоя.' },
    { period: '2016–2019', role: 'Full Stack Engineer', company: 'SaaS-продукт', desc: 'Один продукт целиком: бэкенд, фронтенд и инфраструктура под ними. Основная работа шла с базой под растущей нагрузкой: репликация, чтобы разнести чтение, шардирование, чтобы разнести запись, и кэш на нескольких уровнях с явными правилами, каким данным позволено устаревать. Большая часть выигрыша пришла из чтения планов запросов, а не из нового железа.' },
    { period: '2013–2016', role: 'Full Stack Developer', company: 'Веб-платформа', desc: 'Монолит на классической виртуализации, релизы вручную по чек-листу. Написал первые скрипты развёртывания и перенёс конфигурацию окружений из голов в репозиторий — предок того, что позже стали называть CI/CD. Тогда же стало понятно, что ручной шаг в релизе — это не экономия, а отложенный инцидент.' },
    { period: '2011–2013', role: 'Web Developer', company: 'Веб-студия', desc: 'LAMP на физических серверах: PHP и MySQL, настройка Apache и nginx руками, разбор логов и падений так же. Студия без выделенных админов — за работу сайта после сдачи отвечал тот, кто его написал. Оттуда привычка смотреть на приложение вместе с машиной, на которой оно живёт.' },
  ],
  CATEGORIES: ['All', ...CATEGORIES],
  CATEGORY_LABELS: ['Все', 'Инфраструктура и облако', 'CI/CD и автоматизация', 'Бэкенд', 'Хранение и поиск', 'Фронтенд', 'Наблюдаемость'],
  PROJECTS: [
    // --- Infrastructure (4) ---
    { id: 'bare-to-cloud', name: 'Bare-metal → гибридное облако', cat: 'Infrastructure', tag: 'Migration', stack: 'Terraform, Ansible, AWS, GCP, Linux', desc: 'Уход с серверов, которые вы содержите независимо от того, загружены они или нет. Поэтапно: сначала опись, потом повторение старой конфигурации на новом месте, потом перевод трафика. Бизнес не зависит от одной ночи большого переключения.', metric: '-30-40% расходов / поэтапно' },
    { id: 'k8s-platform', name: 'Kubernetes-платформа', cat: 'Infrastructure', tag: 'Platform', stack: 'Kubernetes, Helm, ArgoCD, Terraform, Prometheus', desc: 'Общая инфраструктура, которой разработчики пользуются, не становясь сначала специалистами по инфраструктуре. Запросили место — получили уже настроенным, и новая работа начинается в тот же день, а не после чужой очереди.', metric: '99.9% аптайм / self-serve namespace' },
    { id: 'iac-baseline', name: 'Инфраструктура как код', cat: 'Infrastructure', tag: 'IaC', stack: 'Terraform, Ansible, GitLab CI, Vault, Linux', desc: 'Каждый сервер описан в файле, поэтому любой из них пересоздаётся с нуля за минуты. Ничего не держится на одной машине, которую боятся трогать, или на правке, сделанной руками два года назад и нигде не записанной.', metric: '100% воспроизводимость / 3 окружения' },
    { id: 'env-parity', name: 'Паритет локали и продакшена', cat: 'Infrastructure', tag: 'Tooling', stack: 'Docker, Docker Compose, Terraform, Make, Linux', desc: 'Ноутбук разработчика, тестовая среда и боевая работают одинаково. Это убирает целую категорию задержек: ошибки, которые вылезают только после релиза, никем не воспроизводятся и разбираются наугад.', metric: 'Один образ / 4 окружения' },
    // --- CI/CD (3) ---
    { id: 'pipeline-standard', name: 'Стандартизированные конвейеры поставки', cat: 'CI/CD', tag: 'Delivery', stack: 'GitLab CI, Jenkins, Docker, Helm, GitHub Actions', desc: 'Один процесс выкладки на все части системы вместо своего у каждой команды. Выпуск изменения превращается из спланированной операции на несколько дней примерно в пятнадцать минут.', metric: '15 мин релиз / десятки сервисов' },
    { id: 'zero-downtime', name: 'Развёртывание без простоя', cat: 'CI/CD', tag: 'Deployment', stack: 'Kubernetes, ArgoCD, NGINX, Helm, Prometheus', desc: 'Обновления выходят без остановки сервиса, а релиз, который начал вести себя плохо, откатывается сам — раньше, чем это увидит большинство клиентов. Никаких заранее объявленных технических окон.', metric: 'Ноль простоя / откат 90 с' },
    { id: 'gitops', name: 'GitOps-модель поставки', cat: 'CI/CD', tag: 'GitOps', stack: 'ArgoCD, Git, Helm, Kustomize, Kubernetes', desc: 'Одна письменная запись о том, как система должна быть настроена, и система сама к ней возвращается. Правки, сделанные руками в три часа ночи, не доживают до того, чтобы стать загадкой следующего месяца.', metric: 'Git как источник истины / авто-сверка' },
    // --- Backend (3) ---
    { id: 'monolith-split', name: 'Монолит на сервисы', cat: 'Backend', tag: 'Architecture', stack: 'PHP, Symfony, Go, gRPC, RabbitMQ', desc: 'Разделение одной большой стареющей системы на части, с которыми можно работать по отдельности, — и всё это время она продолжает обслуживать клиентов. Без заморозки и без переписывания с нуля, которое идёт два года и ничего не отдаёт.', metric: 'Постепенно / без заморозки' },
    { id: 'api-layer', name: 'Слой API и контракты', cat: 'Backend', tag: 'API', stack: 'Node.js, TypeScript, OpenAPI, gRPC, NGINX', desc: 'Письменная договорённость о том, как части системы разговаривают между собой, сгенерированная из одного источника. Если кто-то вносит несовместимое изменение, оно ломается у него на экране при разработке, а не у клиента.', metric: 'Генерация клиентов / версии контрактов' },
    { id: 'async-jobs', name: 'Асинхронная обработка задач', cat: 'Backend', tag: 'Queues', stack: 'Python, FastAPI, Celery, RabbitMQ, Redis', desc: 'Медленная работа — отчёты, импорты, письма, ответы платёжных систем — убрана с пути клиента, чтобы страницы оставались быстрыми. Что не прошло, повторяется безопасно, а если не проходит совсем, попадает туда, куда человек действительно смотрит.', metric: 'Идемпотентные ретраи / разбор DLQ' },
    // --- Data (3) ---
    { id: 'pg-highload', name: 'PostgreSQL под нагрузкой', cat: 'Data', tag: 'Database', stack: 'PostgreSQL, PgBouncer, Patroni, Prometheus, Linux', desc: 'База данных продолжает справляться по мере роста объёма — обычно за счёт того, что выясняется, чем она на самом деле занята, а не за счёт покупки машины помощнее. Дешевле железа и работает дольше.', metric: 'Масштаб чтения / партиционирование' },
    { id: 'cache-tiers', name: 'Многоуровневое кэширование', cat: 'Data', tag: 'Caching', stack: 'Redis, NGINX, CDN, Node.js, PostgreSQL', desc: 'Готовые ответы держатся ближе к посетителю: страницы открываются быстро, серверы работают меньше. У каждого слоя явное правило, насколько он может отстать, поэтому старую цену никто не увидит.', metric: '4 уровня / явная инвалидация' },
    { id: 'search-stack', name: 'Поиск и хранилище документов', cat: 'Data', tag: 'Search', stack: 'Elasticsearch, MongoDB, Python, Kafka, Redis', desc: 'Поиск, который находит по смыслу, а не по точному совпадению слов, и остаётся актуальным по мере изменения каталога. Перестроение индекса идёт при работающем сайте, а не ночью с остановкой.', metric: 'Живая переиндексация / поток изменений' },
    // --- Frontend (2) ---
    { id: 'spa-ssr', name: 'SPA с серверным рендерингом', cat: 'Frontend', tag: 'Web', stack: 'React, TypeScript, Vite, Node.js, NGINX', desc: 'Страницы приходят уже нарисованными: посетитель сразу видит содержимое, а поисковик может его прочитать — дальше сайт ведёт себя как приложение. Лечит частую беду, когда сайт плохо ранжируется, потому что до запуска скриптов он пустой.', metric: 'SSR первая отрисовка / типы сквозные' },
    { id: 'ui-kit', name: 'Библиотека компонентов', cat: 'Frontend', tag: 'Design System', stack: 'Vue.js, TypeScript, Webpack, Storybook, CSS', desc: 'Один набор кнопок, форм и раскладок, из которого собираются все страницы. Новые экраны собираются, а не рисуются заново, выглядят одинаково по умолчанию, и люди с экранными читалками не оказываются забытыми.', metric: '40+ компонентов / WCAG AA' },
    // --- Observability (2) ---
    { id: 'observability', name: 'Стек наблюдаемости', cat: 'Observability', tag: 'Monitoring', stack: 'Prometheus, Grafana, Loki, Elasticsearch, Alertmanager', desc: 'Понимание того, чем занята система, и возможность проследить один запрос клиента насквозь, когда что-то пошло не так. Разница между «сайт как-то тормозит» и знанием, какой именно шаг тормозит и почему.', metric: 'Связанные сигналы / алерты по SLO' },
    { id: 'incident', name: 'Реагирование на инциденты', cat: 'Observability', tag: 'Process', stack: 'Grafana, Alertmanager, Ansible, Git, Linux', desc: 'Понятный ответ на вопрос, кого поднимают ночью, когда что-то сломалось, письменные инструкции, совпадающие с реальностью, и разбор после — дающий исправление, а не виноватого.', metric: 'Дежурства по владению / живые runbook' },
  ],
  ACHIEVEMENTS: [
    { year: '2024', title: 'Последний физический сервер', desc: 'Погасла последняя стойка. Долгой была не перевозка, а инвентаризация: полного списка того, что крутится на железе, не существовало нигде, кроме как в головах трёх человек.' },
    { year: '2022', title: 'Релиз перестал быть событием', desc: 'Выкатка сократилась с многодневной операции примерно до пятнадцати минут, без простоя. Когда релиз дёшев, правки перестают копить до следующего спринта.' },
    { year: '2020', title: 'Конец устной традиции', desc: 'Среды перестали быть уникальными. Расхождение между development, staging и production стало дефектом, а не особенностью жизни.' },
    { year: '2018', title: 'Упирается почти никогда не база', desc: 'Год с хранилищами под нагрузкой: узкое место — почти никогда не движок, а форма вопросов, которые ему задают.' },
    { year: '2016', title: 'DevOps, когда это были два отдела', desc: 'У разработки и эксплуатации были разные цели и разные представления о слове «готово». Инцидент почти никогда не бывает чисто техническим.' },
    { year: '2011', title: 'Первый коммит в продакшен', desc: 'PHP на физическом сервере, деплой по FTP. Работало. Почти — и всё, что выше, отвечает на то, почему «почти» недостаточно.' },
  ],
  CTA_TITLE: 'Начать консультацию',
  CTA_SUB: 'Готовы построить нечто экстраординарное? Одно сообщение запускает разговор.',
  FORM: { NAME: 'Ваше Имя', EMAIL: 'Email Адрес', MESSAGE: 'Опишите ваш проект...', SUBMIT: 'Начать консультацию', SUCCESS: '▸ Сообщение отправлено. Я свяжусь с вами в ближайшее время.', PLACEHOLDER_NAME: 'Имя или лучший псевдоним', PLACEHOLDER_EMAIL: 'туда, где живёт идея', PLACEHOLDER_MSG: 'Продукт, команда, мечта — опишите картину...', CONSENT: 'Согласен на обработку моих данных в порядке, описанном в', CONSENT_LINK: 'политике конфиденциальности', CONSENT_ASK: 'Согласны с политикой конфиденциальности? (y/n)' },
  FORM_ERRORS: {
    CONSENT_REQUIRED: 'Отметьте согласие с политикой конфиденциальности',
    NAME_REQUIRED: 'Введите ваше имя',
    NAME_MIN: 'Имя должно содержать минимум 2 символа',
    NAME_MAX: 'Имя слишком длинное',
    NAME_PATTERN: 'Имя содержит недопустимые символы',
    EMAIL_REQUIRED: 'Введите ваш email',
    EMAIL_INVALID: 'Это не похоже на email',
    EMAIL_PATTERN: 'Это не похоже на email',
    MSG_REQUIRED: 'Опишите ваш проект кратко',
    MSG_MIN: 'Сообщение должно содержать минимум 10 символов',
    MSG_MAX: 'Сообщение слишком длинное (макс. 2000)',
    NETWORK: 'Ошибка сети. Попробуйте позже.',
    RATE_LIMIT: 'Не так быстро. По одному сообщению.',
    DELIVERY_DOWN: 'Отсюда отправить не удалось. Напишите напрямую на {mail}.',
  },
  _PAGE_404: {
    TITLE: '404 — Страница не найдена',
    SUB: 'Этот маршрут не существует.',
    CTA: 'Вернуться на главную',
  },
  BIO: 'Пятнадцать лет строю и масштабирую распределённые системы — застал переход индустрии от bare-metal серверов и монолитов к cloud-native, Kubernetes и GitOps. Берусь за то, что команды откладывают: технический долг, выкладка релизов с нуля и удержание систем в рабочем состоянии.',
  STATS_DESC: 'Миграция инфраструктуры, автоматизация поставки и производительность баз под нагрузкой.',
  ABOUT: 'О себе', CAREER_TITLE: 'Карьера', PROJECTS_TITLE: 'Проекты', ACHIEVEMENTS_TITLE: 'Достижения', SETTINGS: 'Настройки', SETTINGS_LANG: 'Язык', SETTINGS_THEME: 'Тема', SETTINGS_THEME_HINT: '(только для режима Бизнес)', SETTINGS_INTERFACE: 'Интерфейс', SETTINGS_CLOSE: 'Закрыть', MAIL: 'Почта', THEME_DARK: 'Тёмная', THEME_LIGHT: 'Светлая', MODE_BUSINESS: 'Бизнес', MODE_DESKTOP: 'Рабочий стол', MODE_TERMINAL: 'Терминал',
  COFFEE: { TITLE: '☕ Угостить кофе', NETWORK: 'USDT TRC-20', COPY: 'Скопировать адрес', DONE: '✓ Скопировано', CLOSE: 'Закрыть' },
  DETAIL: { BACK: 'Назад', BACK_CAREER: 'Назад к карьере', BACK_ACH: 'Назад к достижениям', NOT_FOUND: 'не найден', KEY_METRICS: 'Ключевые метрики', FEATURES: 'Возможности', TECH_STACK: 'Технологии', KEY_ACH: 'Ключевые достижения', TYPE_PROJECT: 'Проект', TYPE_CAREER: 'Карьера', TYPE_ACH: 'Достижение', PRIVATE_REPO: 'Приватный репозиторий', OPEN_DETAIL: 'Открыть', REFERENCE_NOTE: 'Референсная архитектура. Клиентский код под NDA, поэтому страница описывает устройство системы и логику решений, а не конкретное внедрение.' },
};

const PONYTAIL = Object.freeze({
  SCRUB: 1, DURATION: 600, EASE: 'power2.inOut',
  CATEGORIES,
  LOCALE: { EN, RU },
  SCENES: [
    { id: 'intro', range: [0, 0.18], label: { EN: '15 Years in Code', RU: '15 лет в коде' }, camera: { position: { from: [0, 0, 22], to: [0, 0, 10] }, fov: { from: 60, to: 46 } }, geometry: { type: 'particleLines', particleCount: 10000, spread: 16, assembleSpeed: 0.6 }, postFX: { bloom: { threshold: 0.5, strength: 1.4, radius: 0.5 }, motionBlur: false }, ambient: { gain: 0.5 } },
    { id: 'chronicle', range: [0.18, 0.35], label: { EN: 'Career Timeline', RU: 'Карьерный путь' }, camera: { position: { from: [0, 0, 10], to: [2, -0.5, 7] }, fov: { from: 46, to: 42 } }, geometry: { type: 'timelineMesh', segments: 15, uiEvolution: true }, postFX: { bloom: { threshold: 0.4, strength: 0.9, radius: 0.35 }, motionBlur: false }, ambient: { gain: 0.45 } },
    { id: 'projects', range: [0.35, 0.62], label: { EN: 'Projects & Impact', RU: 'Проекты и влияние' }, camera: { position: { from: [2, -0.5, 7], to: [0, 0.2, 4.5] }, fov: { from: 42, to: 36 } }, geometry: { type: 'graph3d', nodes: [
      { id: 'go', label: 'Go', group: 'backend', size: 3, color: 0x00add8 },
      { id: 'rust', label: 'Rust', group: 'backend', size: 2.5, color: 0xdea584 },
      { id: 'python', label: 'Python', group: 'backend', size: 3, color: 0xffd43b },
      { id: 'ts', label: 'TypeScript', group: 'lang', size: 2.5, color: 0x3178c6 },
      { id: 'k8s', label: 'Kubernetes', group: 'infra', size: 3, color: 0x326ce5 },
      { id: 'kafka', label: 'Kafka', group: 'infra', size: 2.5, color: 0x231f20 },
      { id: 'postgres', label: 'PostgreSQL', group: 'data', size: 2.5, color: 0x336791 },
      { id: 'redis', label: 'Redis', group: 'data', size: 2, color: 0xdc382d },
      { id: 'pytorch', label: 'PyTorch', group: 'ml', size: 2.5, color: 0xee4c2c },
      { id: 'aws', label: 'AWS', group: 'infra', size: 2.5, color: 0xff9900 },
      { id: 'solidity', label: 'Solidity', group: 'blockchain', size: 2, color: 0x888888 },
      { id: 'react', label: 'React', group: 'frontend', size: 2.5, color: 0x61dafb },
      { id: 'temporal', label: 'Temporal', group: 'infra', size: 2, color: 0x4b7bec },
      { id: 'clickhouse', label: 'ClickHouse', group: 'data', size: 2, color: 0xf0c040 },
      { id: 'flink', label: 'Flink', group: 'infra', size: 2, color: 0x0096d6 },
    ], edges: [
      ['go', 'temporal'], ['go', 'kafka'], ['go', 'postgres'], ['go', 'k8s'],
      ['rust', 'kafka'], ['rust', 'clickhouse'],
      ['python', 'pytorch'], ['python', 'aws'], ['python', 'flink'],
      ['ts', 'react'], ['ts', 'solidity'],
      ['k8s', 'aws'], ['k8s', 'temporal'],
      ['postgres', 'redis'], ['kafka', 'flink'],
      ['pytorch', 'aws'], ['solidity', 'ts'],
    ], cameraPath: 'flythrough' }, postFX: { bloom: { threshold: 0.25, strength: 1.6, radius: 0.55 }, motionBlur: { strength: 0.25 } }, ambient: { gain: 0.5 } },
    { id: 'achievements', range: [0.62, 0.80], label: { EN: 'Milestones', RU: 'Достижения' }, camera: { position: { from: [0, 0.2, 4.5], to: [0.5, 0, 3.8] }, fov: { from: 36, to: 32 } }, geometry: { type: 'achievementNodes' }, postFX: { bloom: { threshold: 0.2, strength: 1.9, radius: 0.5 }, motionBlur: false }, ambient: { gain: 0.35 } },
    { id: 'cta', range: [0.80, 1.0], label: { EN: 'Initiate Consult', RU: 'Начать консультацию' }, camera: { position: { from: [0.5, 0, 3.8], to: [0, 0, 2.5] }, fov: { from: 32, to: 28 } }, geometry: { type: 'terminalUI', terminalLines: 12, scanlineEffect: true, glowIntensity: { from: 1.0, to: 1.6 } }, postFX: { bloom: { threshold: 0.15, strength: 2.2, radius: 0.6 }, motionBlur: false }, ambient: { gain: 0.2, fadeOut: true } },
  ],
  SEO: {
    EN: { title: 'Aleksandr Gribakin — Lead Full Stack & DevOps Engineer', description: 'Fifteen years of full stack and DevOps: bare-metal to cloud-native, Kubernetes and GitOps, CI/CD built from nothing, and databases tuned for highload. Go, Node.js, Python, Terraform.', keywords: 'devops engineer, full stack engineer, kubernetes, terraform, ci/cd, gitops, postgresql, highload, aws, gcp' },
    RU: { title: 'Александр Грибакин — Lead Full Stack & DevOps Engineer', description: 'Пятнадцать лет full stack и DevOps: от bare-metal до cloud-native, Kubernetes и GitOps, CI/CD с нуля и базы данных под highload. Go, Node.js, Python, Terraform.', keywords: 'devops инженер, full stack разработчик, kubernetes, terraform, ci/cd, gitops, postgresql, highload, aws, gcp' },
    structuredData: {
      '@context': 'https://schema.org', '@type': 'Person', name: 'Aleksandr Gribakin', givenName: 'Aleksandr', familyName: 'Gribakin',
      email: 'RF24KRSK@gmail.com', url: 'https://dev24.pro',
      knowsAbout: ['DevOps', 'Kubernetes', 'Infrastructure as Code', 'CI/CD', 'Terraform', 'Ansible', 'Docker', 'PostgreSQL', 'Go', 'Node.js', 'Python', 'React', 'AWS', 'Google Cloud', 'Distributed Systems'],
      // sameAs asserts identity to search engines. The old GitHub URL pointed at
      // an account with zero public repositories. Add profile URLs here only
      // once they are real and yours.
      sameAs: [],
    },
  },
});

export default PONYTAIL;
