const CATEGORIES = ['Infrastructure', 'CI/CD', 'Backend', 'Data', 'Frontend', 'Observability'];

const EN = {
  NAME: 'ALEKSANDR GRIBAKIN', TAGLINE: '15 Years in Code', SKIP_LINK: 'Skip to content',
  ROLE: 'Lead Full Stack & DevOps Engineer',
  INTRO_SUB: 'Building systems that scale. Automating what should never have been manual.',
  SECTION_TITLES: { STATS: 'Impact By The Numbers', CAREER: 'Career Timeline', PROJECTS: 'Projects & Impact', ACHIEVEMENTS: 'Milestones & Recognition' },
  BOOT_LINES: ['DECRYPTING_IDENTITY... OK', 'SCANNING_CREDENTIALS... OK', 'LOADING_PORTFOLIO... OK', 'ESTABLISHING_SECURE_CHANNEL... OK', 'WELCOME://ALEKSANDR.GRIBAKIN'],
  // Headline numbers are computed in src/lib/stats.js from the content below —
  // only their wording lives here, so a figure can never contradict the data.
  STATS_LABELS: {
    EXPERIENCE: 'Years in Production', EXPERIENCE_HINT: 'Shipping professionally since {year}',
    PROJECTS: 'Projects Shipped', PROJECTS_HINT: 'Across {n} domains',
    STACK: 'Technologies Shipped', STACK_HINT: 'Most used: {top}',
    CAPABILITIES: 'Capabilities Shipped', CAPABILITIES_HINT: 'Across {n} systems, all closed-source',
    AVAILABILITY: 'Availability Target', AVAILABILITY_HINT: 'Highest of {n} tracked quality metrics',
    MILESTONES: 'Milestones & Recognition', MILESTONES_HINT: '{from} → {to}',
    UNIT_YEARS: 'yrs', UNIT_PROJECTS: 'projects',
    EXPAND: 'Show breakdown', COLLAPSE: 'Hide breakdown',
  },
  METRIC: {
    HIGHER_BETTER: 'higher is better', LOWER_BETTER: 'lower is better',
    RANK: 'rank {r} of {n} in this portfolio', OF_TARGET: 'of 100%',
    SCALE_NOTE: 'Bar length shows how this value sits against every comparable metric across all projects.',
  },
  DASHBOARD: {
    TITLE: 'Selection at a glance',
    PROJECTS: 'projects', TECH: 'technologies', REPOS: 'under NDA', FEATURES: 'shipped features',
    TOP_TECH: 'Most used in this selection',
    SORT: 'Sort', SORT_DEFAULT: 'Default', SORT_SCALE: 'By scale', SORT_STACK: 'By stack depth',
  },
  TERMINAL: {
    ACCESS: 'ACCESS GRANTED',
    BOOT_CLIENT: 'Client', BOOT_SESSION: 'Session', BOOT_TARGET: 'Target', BOOT_SHELL: 'Shell',
    WELCOME: 'Type `help` to see what this thing does.',
    HEAD_HELP: 'AVAILABLE COMMANDS', HEAD_ID: 'IDENTITY', HEAD_ABOUT: 'ABOUT',
    HEAD_STATS: 'SYSTEM PROFILE', HEAD_CAREER: 'CAREER LOG', HEAD_TARGETS: 'TARGETS',
    HEAD_STACK: 'TECHNOLOGY', HEAD_MILESTONES: 'MILESTONES', HEAD_TRANSMIT: 'TRANSMIT',
    HEAD_METRICS: 'KEY METRICS', HEAD_FEATURES: 'FEATURES',
    CMD: {
      HELP: 'this list', WHOAMI: 'who you are talking to', ABOUT: 'the short version',
      STATS: 'headline numbers, computed from the content', CAREER: 'career log, or one entry in full',
      PROJECTS: 'list the reference architectures', OPEN: 'full brief on one of them',
      STACK: 'technology, by how often it appears', ACH: 'milestones, or one in full',
      CONTACT: 'send a message from here', LANG: 'switch language', MODE: 'leave for another interface',
      NEOFETCH: 'the obligatory one', COFFEE: 'buy me one', HISTORY: 'what you have typed',
      CLEAR: 'wipe the screen', EXIT: 'back to the standard view',
    },
    HINT_KEYS: 'Tab completes · ↑ ↓ history · Ctrl+L clears · Ctrl+C aborts',
    HINT_BREAKDOWN: 'Run `stats --breakdown` for the charts.',
    HINT_DETAIL: 'career {n} for the full entry',
    HINT_DETAIL_N: 'achievements {n}',
    HINT_OPEN: 'open <id> for the full brief',
    HINT_LS: 'Run `projects` to list them.',
    HINT_HELP: 'Type `help` for the list.',
    NOT_FOUND: 'command not found: {c}',
    NO_ENTRY: 'No entry {n}.', NO_CAT: 'No category matching "{c}".', NO_TARGET: 'No target "{id}".',
    USAGE_OPEN: 'usage: open <project-id>',
    LBL_STACK: 'Stack', LBL_CAT: 'Category', LBL_ACCESS: 'Access',
    LANG_CURRENT: 'Language: {l}. Usage: lang <en|ru>', LANG_SET: 'Language set to {l}.',
    MODE_USAGE: 'usage: mode <business|desktop>', MODE_SET: 'Switching to {m}…',
    TRANSMIT_INTRO: 'Direct line. Three questions, then it sends.',
    TRANSMIT_CANCEL: 'Ctrl+C to abort.', TRANSMIT_PROMPT: 'transmit>', TRANSMIT_ABORTED: '^C aborted.',
    ASK_NAME: 'Your name?', ASK_EMAIL: 'Email to reply to?', ASK_MESSAGE: 'What are you building?',
    SENDING: 'Transmitting…', SENT: 'TRANSMISSION SENT (200 OK)',
    SEND_FAIL: 'TRANSMISSION FAILED ({e})', SEND_FALLBACK: 'Mail directly: {mail}',
    SUDO: 'visitor is not in the sudoers file. This incident has been reported.',
    NO_HISTORY: 'No history yet.',
    EXIT: 'Session closed. Returning to the standard view…',
  },
  CAREER: [
    { period: '2022–2026', role: 'Senior DevOps / Platform Engineer', company: 'Cloud-native platform', desc: 'Ran the Kubernetes platform product teams build on: a namespace arrives with quotas, ingress, TLS and monitoring already wired together, so shipping a service does not require learning the cluster. Delivery moved to GitOps — the repository holds the desired state, and anything changed by hand on the cluster is reverted automatically. The last physical servers went into hybrid cloud; maintenance spend fell 30–40%.' },
    { period: '2019–2022', role: 'DevOps Engineer', company: 'Microservices migration', desc: 'Dozens of microservices, each with a hand-built pipeline that had long since drifted from its neighbours. Reduced them to one template: a service declares its type and gets build, tests and deployment already assembled. Releasing stopped being a coordinated multi-day event — about fifteen minutes now, with no downtime.' },
    { period: '2016–2019', role: 'Full Stack Engineer', company: 'SaaS product', desc: 'One product end to end: backend, frontend and the infrastructure under both. Most of the work was the database under growing load — replication to spread reads, sharding to spread writes, and caching in tiers with explicit rules about which data is allowed to go stale. Most of the gain came from reading query plans rather than from buying hardware.' },
    { period: '2013–2016', role: 'Full Stack Developer', company: 'Web platform', desc: 'A monolith on classic virtualisation, released by hand against a checklist. Wrote the first deployment scripts and moved environment configuration out of people’s heads and into the repository — the ancestor of what later got called CI/CD. This is where it became clear that a manual step in a release is not saved effort, it is a deferred incident.' },
    { period: '2011–2013', role: 'Web Developer', company: 'Digital agency', desc: 'LAMP on physical servers: PHP and MySQL, Apache and nginx tuned by hand, logs and crashes read the same way. An agency with no dedicated sysadmins — whoever wrote the site kept it running after handover. That is where the habit of looking at an application together with the machine it lives on comes from.' },
  ],
  CATEGORIES: ['All', ...CATEGORIES],
  CATEGORY_LABELS: ['All', 'Infrastructure & Cloud', 'CI/CD & Automation', 'Backend', 'Data & Storage', 'Frontend', 'Observability'],
  PROJECTS: [
    // --- Infrastructure (4) ---
    { id: 'bare-to-cloud', name: 'Bare-Metal to Hybrid Cloud', cat: 'Infrastructure', tag: 'Migration', stack: 'Terraform, Ansible, AWS, GCP, Linux', desc: 'Staged migration off physical servers into hybrid cloud. Inventory first, then parity, then traffic — never all three at once.', metric: '30-40% cost cut / staged cutover' },
    { id: 'k8s-platform', name: 'Kubernetes Platform', cat: 'Infrastructure', tag: 'Platform', stack: 'Kubernetes, Helm, ArgoCD, Terraform, Prometheus', desc: 'A cluster product teams can use without learning Kubernetes. Namespaces, quotas, ingress and monitoring arrive with the namespace.', metric: '99.9% uptime / self-serve namespaces' },
    { id: 'iac-baseline', name: 'Infrastructure as Code Baseline', cat: 'Infrastructure', tag: 'IaC', stack: 'Terraform, Ansible, GitLab CI, Vault, Linux', desc: 'Every environment described in code and rebuilt from zero on demand. No snowflake servers, no undocumented hand edits.', metric: '100% reproducible / 3 environments' },
    { id: 'env-parity', name: 'Local and Production Parity', cat: 'Infrastructure', tag: 'Tooling', stack: 'Docker, Docker Compose, Terraform, Make, Linux', desc: 'The same images and the same configuration shape everywhere. Kills the "works on my machine" class of bug outright.', metric: 'One image / 4 environments' },
    // --- CI/CD (3) ---
    { id: 'pipeline-standard', name: 'Standardised Delivery Pipelines', cat: 'CI/CD', tag: 'Delivery', stack: 'GitLab CI, Jenkins, Docker, Helm, GitHub Actions', desc: 'One pipeline template across dozens of services. Release time from days to about fifteen minutes.', metric: '15 min release / dozens of services' },
    { id: 'zero-downtime', name: 'Zero-Downtime Deployment', cat: 'CI/CD', tag: 'Deployment', stack: 'Kubernetes, ArgoCD, NGINX, Helm, Prometheus', desc: 'Rolling and blue-green releases with health-gated promotion. A bad release rolls back before most users notice.', metric: 'Zero downtime / 90s rollback' },
    { id: 'gitops', name: 'GitOps Delivery Model', cat: 'CI/CD', tag: 'GitOps', stack: 'ArgoCD, Git, Helm, Kustomize, Kubernetes', desc: 'The repository is the desired state. Anything applied by hand gets reverted by the reconciler, on purpose.', metric: 'Git as source of truth / auto-reconcile' },
    // --- Backend (3) ---
    { id: 'monolith-split', name: 'Monolith to Services', cat: 'Backend', tag: 'Architecture', stack: 'PHP, Symfony, Go, gRPC, RabbitMQ', desc: 'Strangler-fig extraction with the monolith serving traffic throughout. Seams chosen by data ownership, not by folder layout.', metric: 'Incremental cutover / no freeze' },
    { id: 'api-layer', name: 'API Layer and Contracts', cat: 'Backend', tag: 'API', stack: 'Node.js, TypeScript, OpenAPI, gRPC, NGINX', desc: 'REST outward, gRPC inward, one generated contract for both. Clients break at build time instead of in production.', metric: 'Generated clients / versioned contracts' },
    { id: 'async-jobs', name: 'Async Job Processing', cat: 'Backend', tag: 'Queues', stack: 'Python, FastAPI, Celery, RabbitMQ, Redis', desc: 'Queue-backed background work with idempotent handlers, retries with backoff and a dead-letter queue that gets read.', metric: 'Idempotent retries / DLQ triage' },
    // --- Data (3) ---
    { id: 'pg-highload', name: 'PostgreSQL Under Load', cat: 'Data', tag: 'Database', stack: 'PostgreSQL, PgBouncer, Patroni, Prometheus, Linux', desc: 'Replication, partitioning and connection pooling. Most wins came from reading query plans, not from adding hardware.', metric: 'Read scale-out / partitioned writes' },
    { id: 'cache-tiers', name: 'Multi-Level Caching', cat: 'Data', tag: 'Caching', stack: 'Redis, NGINX, CDN, Node.js, PostgreSQL', desc: 'CDN, edge, application and query caches with explicit invalidation. Every layer answers what it is allowed to be wrong about.', metric: '4 tiers / explicit invalidation' },
    { id: 'search-stack', name: 'Search and Document Store', cat: 'Data', tag: 'Search', stack: 'Elasticsearch, MongoDB, Python, Kafka, Redis', desc: 'Full-text search fed by a change stream, with reindexing that runs against live traffic instead of a maintenance window.', metric: 'Live reindex / change-stream fed' },
    // --- Frontend (2) ---
    { id: 'spa-ssr', name: 'SPA with Server-Side Rendering', cat: 'Frontend', tag: 'Web', stack: 'React, TypeScript, Vite, Node.js, NGINX', desc: 'Rendered on the server for first paint and crawlers, hydrated on the client for everything after.', metric: 'SSR first paint / typed end to end' },
    { id: 'ui-kit', name: 'Component Library', cat: 'Frontend', tag: 'Design System', stack: 'Vue.js, TypeScript, Webpack, Storybook, CSS', desc: 'A shared component set with tokens, documented states and accessibility built in rather than retrofitted.', metric: '40+ components / WCAG AA' },
    // --- Observability (2) ---
    { id: 'observability', name: 'Observability Stack', cat: 'Observability', tag: 'Monitoring', stack: 'Prometheus, Grafana, Loki, Elasticsearch, Alertmanager', desc: 'Metrics, logs and traces correlated by request id. Dashboards answer questions instead of displaying numbers.', metric: 'Correlated signals / SLO-based alerts' },
    { id: 'incident', name: 'Incident Response', cat: 'Observability', tag: 'Process', stack: 'Grafana, Alertmanager, Ansible, Git, Linux', desc: 'On-call with owned services, runbooks that are actually current, and postmortems that produce changes rather than blame.', metric: 'Owned rotations / current runbooks' },
  ],
  // Milestones describe work inside employers, not public records. Nothing here
  // claims a patent, a conference programme slot, a journal byline or a
  // repository star count — those are all externally verifiable, and inventing
  // one is forgery rather than a CV claim.
  ACHIEVEMENTS: [
    { year: '2024', title: 'Off Bare Metal', desc: 'Moved a legacy estate from physical servers and classic virtualisation into hybrid cloud on AWS and GCP. Maintenance spend fell 30-40%.' },
    { year: '2022', title: 'Release Time: Days to Minutes', desc: 'Standardised CI/CD across dozens of microservices. Deployment went from a multi-day event to roughly fifteen minutes, with no downtime.' },
    { year: '2021', title: 'Conferences and Community', desc: 'Regular at HighLoad++, DevOpsConf and regional meetups through the years the industry rebuilt itself. Took the floor in discussions on monolith migration, CI/CD before Docker was ubiquitous, and database tuning under load — as a practitioner in the room, not a billed speaker.' },
    { year: '2020', title: 'Infrastructure as Code', desc: 'Automated configuration management and environment provisioning end to end. Development, staging and production became reproducible rather than hand-assembled.' },
    { year: '2018', title: 'Databases Under Load', desc: 'Tuned relational and non-relational stores for highload: sharding, replication and a multi-level cache strategy instead of one more read replica.' },
    { year: '2016', title: 'DevOps as a Practice', desc: 'Became the link between development and operations back when those were separate departments with separate incentives. Mentored engineers on both sides of that line.' },
    { year: '2011', title: 'First Production Commit', desc: 'A PHP application on a physical server, deployed over FTP. It worked. Mostly. It also taught me exactly why none of that is acceptable now.' },
  ],
  CTA_TITLE: 'Initiate Consult',
  CTA_SUB: 'Ready to build something extraordinary? One message starts the conversation.',
  FORM: { NAME: 'Your Name', EMAIL: 'Email Address', MESSAGE: 'Describe your project...', SUBMIT: 'Initiate Consult', SUCCESS: '▸ Message transmitted. I will reach out shortly.', PLACEHOLDER_NAME: 'Your name, or your best alias', PLACEHOLDER_EMAIL: 'where pixels meet purpose', PLACEHOLDER_MSG: 'Product, team, dream — paint the picture...' },
  FORM_ERRORS: {
    NAME_REQUIRED: 'Enter your name',
    NAME_MIN: 'Name must be at least 2 characters',
    NAME_MAX: 'Name is too long',
    NAME_PATTERN: 'Name contains invalid characters',
    EMAIL_REQUIRED: 'Enter your email',
    EMAIL_INVALID: 'That does not look like an email',
    EMAIL_PATTERN: 'That does not look like an email',
    MSG_REQUIRED: 'Describe your project briefly',
    MSG_MIN: 'Message must be at least 10 characters',
    MSG_MAX: 'Message is too long (max 2000)',
    NETWORK: 'Network error. Try again later.',
    RATE_LIMIT: 'Slow down. One message at a time.',
    DELIVERY_DOWN: 'Could not send from here. Please write to {mail} directly.',
  },
  _PAGE_404: {
    TITLE: '404 — Page Not Found',
    SUB: 'This route does not exist.',
    CTA: 'Return Home',
  },
  BIO: 'Fifteen years building and scaling distributed systems, across the industry\'s move from bare-metal servers and monoliths to cloud-native, Kubernetes and GitOps. I take on the work teams postpone: technical debt, CI/CD built from nothing, and keeping things up.',
  STATS_DESC: 'Infrastructure migration, delivery automation and database performance under load.',
  ABOUT: 'About', CAREER_TITLE: 'Career', PROJECTS_TITLE: 'Projects', ACHIEVEMENTS_TITLE: 'Achievements', SETTINGS: 'Settings', SETTINGS_LANG: 'Language', MAIL: 'Mail', THEME_DARK: 'Dark', THEME_LIGHT: 'Light', MODE_BUSINESS: 'Business', MODE_DESKTOP: 'Desktop', MODE_TERMINAL: 'Terminal',
  COFFEE: { TITLE: '☕ Buy me a coffee', NETWORK: 'USDT TRC-20', COPY: 'Copy Address', DONE: '✓ Copied', CLOSE: 'Close' },
  DETAIL: { BACK: 'Back', BACK_CAREER: 'Back to Career', BACK_ACH: 'Back to Achievements', NOT_FOUND: 'not found', KEY_METRICS: 'Key Metrics', FEATURES: 'Features', TECH_STACK: 'Tech Stack', KEY_ACH: 'Key Achievements', TYPE_PROJECT: 'Project', TYPE_CAREER: 'Career', TYPE_ACH: 'Achievement', PRIVATE_REPO: 'Private repository', OPEN_DETAIL: 'Open', REFERENCE_NOTE: 'Reference architecture. Client code is under NDA, so this page describes the design and the reasoning behind it rather than a specific deployment.' },
};

const RU = {
  NAME: 'АЛЕКСАНДР ГРИБАКИН', TAGLINE: '15 лет в коде', SKIP_LINK: 'Перейти к содержанию',
  ROLE: 'Lead Full Stack & DevOps Engineer',
  INTRO_SUB: 'Строю системы, которые масштабируются. Автоматизирую то, что никогда не должно было делаться руками.',
  SECTION_TITLES: { STATS: 'Влияние в цифрах', CAREER: 'Карьерный путь', PROJECTS: 'Проекты и влияние', ACHIEVEMENTS: 'Вехи и признание' },
  BOOT_LINES: ['ДЕШИФРОВКА_ЛИЧНОСТИ... OK', 'ПРОВЕРКА_ПОЛНОМОЧИЙ... OK', 'ЗАГРУЗКА_ПОРТФОЛИО... OK', 'УСТАНОВКА_БЕЗОПАСНОГО_КАНАЛА... OK', 'ДОБРО_ПОЖАЛОВАТЬ://АЛЕКСАНДР.ГРИБАКИН'],
  STATS_LABELS: {
    EXPERIENCE: 'Лет в продакшене', EXPERIENCE_HINT: 'Профессионально с {year} года',
    PROJECTS: 'Проектов в продакшене', PROJECTS_HINT: 'В {n} направлениях',
    STACK: 'Технологий в бою', STACK_HINT: 'Чаще всего: {top}',
    CAPABILITIES: 'Реализовано возможностей', CAPABILITIES_HINT: 'В {n} системах, все с закрытым кодом',
    AVAILABILITY: 'Целевая доступность', AVAILABILITY_HINT: 'Лучший из {n} отслеживаемых показателей качества',
    MILESTONES: 'Вехи и признание', MILESTONES_HINT: '{from} → {to}',
    UNIT_YEARS: 'лет', UNIT_PROJECTS: 'проектов',
    EXPAND: 'Показать разбивку', COLLAPSE: 'Скрыть разбивку',
  },
  METRIC: {
    HIGHER_BETTER: 'больше — лучше', LOWER_BETTER: 'меньше — лучше',
    RANK: 'место {r} из {n} в портфолио', OF_TARGET: 'из 100%',
    SCALE_NOTE: 'Длина полосы показывает, как значение выглядит на фоне всех сопоставимых метрик по всем проектам.',
  },
  DASHBOARD: {
    TITLE: 'Выборка в цифрах',
    PROJECTS: 'проектов', TECH: 'технологий', REPOS: 'под NDA', FEATURES: 'реализованных возможностей',
    TOP_TECH: 'Чаще всего в этой выборке',
    SORT: 'Сортировка', SORT_DEFAULT: 'По умолчанию', SORT_SCALE: 'По масштабу', SORT_STACK: 'По глубине стека',
  },
  TERMINAL: {
    ACCESS: 'ДОСТУП РАЗРЕШЁН',
    BOOT_CLIENT: 'Клиент', BOOT_SESSION: 'Сессия', BOOT_TARGET: 'Цель', BOOT_SHELL: 'Оболочка',
    WELCOME: 'Введите `help`, чтобы узнать, что тут умеют.',
    HEAD_HELP: 'ДОСТУПНЫЕ КОМАНДЫ', HEAD_ID: 'ЛИЧНОСТЬ', HEAD_ABOUT: 'О СЕБЕ',
    HEAD_STATS: 'ПРОФИЛЬ СИСТЕМЫ', HEAD_CAREER: 'ЖУРНАЛ КАРЬЕРЫ', HEAD_TARGETS: 'ЦЕЛИ',
    HEAD_STACK: 'ТЕХНОЛОГИИ', HEAD_MILESTONES: 'ВЕХИ', HEAD_TRANSMIT: 'ПЕРЕДАЧА',
    HEAD_METRICS: 'КЛЮЧЕВЫЕ МЕТРИКИ', HEAD_FEATURES: 'ВОЗМОЖНОСТИ',
    CMD: {
      HELP: 'этот список', WHOAMI: 'с кем вы говорите', ABOUT: 'коротко о главном',
      STATS: 'цифры, вычисленные из контента', CAREER: 'журнал карьеры или одна запись целиком',
      PROJECTS: 'список референсных архитектур', OPEN: 'полная справка по одной из них',
      STACK: 'технологии по частоте появления', ACH: 'вехи или одна целиком',
      CONTACT: 'отправить сообщение прямо отсюда', LANG: 'сменить язык', MODE: 'уйти в другой интерфейс',
      NEOFETCH: 'та самая команда', COFFEE: 'угостить кофе', HISTORY: 'что вы вводили',
      CLEAR: 'очистить экран', EXIT: 'вернуться к обычному виду',
    },
    HINT_KEYS: 'Tab дополняет · ↑ ↓ история · Ctrl+L очищает · Ctrl+C прерывает',
    HINT_BREAKDOWN: 'Введите `stats --breakdown` для графиков.',
    HINT_DETAIL: 'career {n} — запись целиком',
    HINT_DETAIL_N: 'achievements {n}',
    HINT_OPEN: 'open <id> — полная справка',
    HINT_LS: 'Введите `projects`, чтобы увидеть список.',
    HINT_HELP: 'Введите `help` для списка.',
    NOT_FOUND: 'команда не найдена: {c}',
    NO_ENTRY: 'Записи {n} нет.', NO_CAT: 'Категория "{c}" не найдена.', NO_TARGET: 'Цель "{id}" не найдена.',
    USAGE_OPEN: 'использование: open <project-id>',
    LBL_STACK: 'Стек', LBL_CAT: 'Категория', LBL_ACCESS: 'Доступ',
    LANG_CURRENT: 'Язык: {l}. Использование: lang <en|ru>', LANG_SET: 'Язык переключён на {l}.',
    MODE_USAGE: 'использование: mode <business|desktop>', MODE_SET: 'Переключаюсь на {m}…',
    TRANSMIT_INTRO: 'Прямая линия. Три вопроса — и уходит.',
    TRANSMIT_CANCEL: 'Ctrl+C — прервать.', TRANSMIT_PROMPT: 'transmit>', TRANSMIT_ABORTED: '^C прервано.',
    ASK_NAME: 'Как вас зовут?', ASK_EMAIL: 'На какой email отвечать?', ASK_MESSAGE: 'Что вы строите?',
    SENDING: 'Передаю…', SENT: 'СООБЩЕНИЕ ОТПРАВЛЕНО (200 OK)',
    SEND_FAIL: 'ПЕРЕДАЧА НЕ УДАЛАСЬ ({e})', SEND_FALLBACK: 'Написать напрямую: {mail}',
    SUDO: 'visitor отсутствует в файле sudoers. Инцидент запротоколирован.',
    NO_HISTORY: 'История пуста.',
    EXIT: 'Сессия закрыта. Возвращаюсь к обычному виду…',
  },
  CAREER: [
    { period: '2022–2026', role: 'Senior DevOps / Platform Engineer', company: 'Cloud-native платформа', desc: 'Вёл Kubernetes-платформу, на которой работают продуктовые команды: неймспейс выдаётся сразу с квотами, ingress, TLS и мониторингом, и чтобы выкатить сервис, разбираться в устройстве кластера не нужно. Поставку перевёл на GitOps: нужное состояние описано в репозитории, а правки руками на кластере откатываются автоматически. Последние физические серверы ушли в гибридное облако, обслуживание подешевело на 30–40%.' },
    { period: '2019–2022', role: 'DevOps Engineer', company: 'Миграция на микросервисы', desc: 'Десятки микросервисов, у каждого свой самописный пайплайн, давно разошедшийся с соседними. Свёл их к одному шаблону: сервис объявляет свой тип и получает готовую сборку, тесты и выкатку. Релиз перестал быть согласованным событием на несколько дней — теперь это около пятнадцати минут и без простоя.' },
    { period: '2016–2019', role: 'Full Stack Engineer', company: 'SaaS-продукт', desc: 'Один продукт целиком: бэкенд, фронтенд и инфраструктура под ними. Основная работа шла с базой под растущей нагрузкой: репликация, чтобы разнести чтение, шардирование, чтобы разнести запись, и кэш на нескольких уровнях с явными правилами, каким данным позволено устаревать. Большая часть выигрыша пришла из чтения планов запросов, а не из нового железа.' },
    { period: '2013–2016', role: 'Full Stack Developer', company: 'Веб-платформа', desc: 'Монолит на классической виртуализации, релизы вручную по чек-листу. Написал первые скрипты развёртывания и перенёс конфигурацию окружений из голов в репозиторий — предок того, что позже стали называть CI/CD. Тогда же стало понятно, что ручной шаг в релизе — это не экономия, а отложенный инцидент.' },
    { period: '2011–2013', role: 'Web Developer', company: 'Веб-студия', desc: 'LAMP на физических серверах: PHP и MySQL, настройка Apache и nginx руками, разбор логов и падений так же. Студия без выделенных админов — за работу сайта после сдачи отвечал тот, кто его написал. Оттуда привычка смотреть на приложение вместе с машиной, на которой оно живёт.' },
  ],
  CATEGORIES: ['All', ...CATEGORIES],
  CATEGORY_LABELS: ['Все', 'Инфраструктура и облако', 'CI/CD и автоматизация', 'Бэкенд', 'Данные и хранилища', 'Фронтенд', 'Наблюдаемость'],
  PROJECTS: [
    // --- Infrastructure (4) ---
    { id: 'bare-to-cloud', name: 'Bare-metal → гибридное облако', cat: 'Infrastructure', tag: 'Migration', stack: 'Terraform, Ansible, AWS, GCP, Linux', desc: 'Поэтапный уход с физических серверов в гибридное облако. Сначала инвентаризация, потом паритет, потом трафик — но не всё сразу.', metric: '-30-40% расходов / поэтапно' },
    { id: 'k8s-platform', name: 'Kubernetes-платформа', cat: 'Infrastructure', tag: 'Platform', stack: 'Kubernetes, Helm, ArgoCD, Terraform, Prometheus', desc: 'Кластер, которым продуктовые команды пользуются, не изучая Kubernetes. Namespace приходит сразу с квотами, ingress и мониторингом.', metric: '99.9% аптайм / self-serve namespace' },
    { id: 'iac-baseline', name: 'Инфраструктура как код', cat: 'Infrastructure', tag: 'IaC', stack: 'Terraform, Ansible, GitLab CI, Vault, Linux', desc: 'Каждое окружение описано кодом и пересоздаётся с нуля по требованию. Ни серверов-снежинок, ни недокументированных правок руками.', metric: '100% воспроизводимость / 3 окружения' },
    { id: 'env-parity', name: 'Паритет локали и продакшена', cat: 'Infrastructure', tag: 'Tooling', stack: 'Docker, Docker Compose, Terraform, Make, Linux', desc: 'Одни и те же образы и одна форма конфигурации везде. Убирает класс багов «на моей машине работает» целиком.', metric: 'Один образ / 4 окружения' },
    // --- CI/CD (3) ---
    { id: 'pipeline-standard', name: 'Стандартизированные конвейеры поставки', cat: 'CI/CD', tag: 'Delivery', stack: 'GitLab CI, Jenkins, Docker, Helm, GitHub Actions', desc: 'Один шаблон пайплайна на десятки сервисов. Время релиза с дней до примерно пятнадцати минут.', metric: '15 мин релиз / десятки сервисов' },
    { id: 'zero-downtime', name: 'Развёртывание без простоя', cat: 'CI/CD', tag: 'Deployment', stack: 'Kubernetes, ArgoCD, NGINX, Helm, Prometheus', desc: 'Rolling и blue-green релизы с промоушеном по здоровью. Плохой релиз откатывается раньше, чем его заметит большинство.', metric: 'Ноль простоя / откат 90 с' },
    { id: 'gitops', name: 'GitOps-модель поставки', cat: 'CI/CD', tag: 'GitOps', stack: 'ArgoCD, Git, Helm, Kustomize, Kubernetes', desc: 'Репозиторий и есть желаемое состояние. Всё применённое руками откатывается контроллером — это задумано.', metric: 'Git как источник истины / авто-сверка' },
    // --- Backend (3) ---
    { id: 'monolith-split', name: 'Монолит на сервисы', cat: 'Backend', tag: 'Architecture', stack: 'PHP, Symfony, Go, gRPC, RabbitMQ', desc: 'Извлечение по strangler fig, монолит всё время обслуживает трафик. Границы по владению данными, а не по структуре папок.', metric: 'Постепенно / без заморозки' },
    { id: 'api-layer', name: 'Слой API и контракты', cat: 'Backend', tag: 'API', stack: 'Node.js, TypeScript, OpenAPI, gRPC, NGINX', desc: 'REST наружу, gRPC внутрь, один сгенерированный контракт на оба. Клиенты ломаются на сборке, а не в продакшене.', metric: 'Генерация клиентов / версии контрактов' },
    { id: 'async-jobs', name: 'Асинхронная обработка задач', cat: 'Backend', tag: 'Queues', stack: 'Python, FastAPI, Celery, RabbitMQ, Redis', desc: 'Фоновая работа через очереди: идемпотентные обработчики, ретраи с backoff и dead-letter, который действительно читают.', metric: 'Идемпотентные ретраи / разбор DLQ' },
    // --- Data (3) ---
    { id: 'pg-highload', name: 'PostgreSQL под нагрузкой', cat: 'Data', tag: 'Database', stack: 'PostgreSQL, PgBouncer, Patroni, Prometheus, Linux', desc: 'Репликация, партиционирование и пулинг соединений. Основной выигрыш пришёл от чтения планов запросов, а не от железа.', metric: 'Масштаб чтения / партиционирование' },
    { id: 'cache-tiers', name: 'Многоуровневое кэширование', cat: 'Data', tag: 'Caching', stack: 'Redis, NGINX, CDN, Node.js, PostgreSQL', desc: 'CDN, edge, приложение и запросы с явной инвалидацией. Каждый слой отвечает за то, в чём ему позволено ошибаться.', metric: '4 уровня / явная инвалидация' },
    { id: 'search-stack', name: 'Поиск и хранилище документов', cat: 'Data', tag: 'Search', stack: 'Elasticsearch, MongoDB, Python, Kafka, Redis', desc: 'Полнотекстовый поиск на потоке изменений, переиндексация идёт под живым трафиком, а не в техническое окно.', metric: 'Живая переиндексация / поток изменений' },
    // --- Frontend (2) ---
    { id: 'spa-ssr', name: 'SPA с серверным рендерингом', cat: 'Frontend', tag: 'Web', stack: 'React, TypeScript, Vite, Node.js, NGINX', desc: 'Рендер на сервере ради первой отрисовки и поисковиков, гидратация на клиенте для всего остального.', metric: 'SSR первая отрисовка / типы сквозные' },
    { id: 'ui-kit', name: 'Библиотека компонентов', cat: 'Frontend', tag: 'Design System', stack: 'Vue.js, TypeScript, Webpack, Storybook, CSS', desc: 'Общий набор компонентов с токенами, описанными состояниями и доступностью, заложенной сразу, а не потом.', metric: '40+ компонентов / WCAG AA' },
    // --- Observability (2) ---
    { id: 'observability', name: 'Стек наблюдаемости', cat: 'Observability', tag: 'Monitoring', stack: 'Prometheus, Grafana, Loki, Elasticsearch, Alertmanager', desc: 'Метрики, логи и трейсы связаны id запроса. Дашборды отвечают на вопросы, а не показывают числа.', metric: 'Связанные сигналы / алерты по SLO' },
    { id: 'incident', name: 'Реагирование на инциденты', cat: 'Observability', tag: 'Process', stack: 'Grafana, Alertmanager, Ansible, Git, Linux', desc: 'Дежурства по владению сервисом, runbook в актуальном состоянии и постмортемы, дающие изменения, а не виноватых.', metric: 'Дежурства по владению / живые runbook' },
  ],
  ACHIEVEMENTS: [
    { year: '2024', title: 'Уход с bare-metal', desc: 'Перевёл legacy-инфраструктуру с физических серверов и классической виртуализации в гибридное облако на AWS и GCP. Расходы на обслуживание упали на 30-40%.' },
    { year: '2022', title: 'Релиз: с дней до минут', desc: 'Стандартизировал CI/CD для десятков микросервисов. Развёртывание превратилось из многодневного события примерно в пятнадцать минут, без простоя.' },
    { year: '2021', title: 'Конференции и сообщество', desc: 'Постоянный участник HighLoad++, DevOpsConf и региональных митапов в годы, когда индустрия себя перестраивала. Выступал в обсуждениях о миграции монолита, CI/CD до повсеместного Docker и тюнинге СУБД под нагрузкой — как практик из зала, а не заявленный докладчик.' },
    { year: '2020', title: 'Инфраструктура как код', desc: 'Автоматизировал управление конфигурациями и развёртывание сред целиком. Development, staging и production стали воспроизводимыми, а не собранными вручную.' },
    { year: '2018', title: 'Базы под нагрузкой', desc: 'Настраивал реляционные и нереляционные хранилища под highload: шардирование, репликация и многоуровневое кэширование вместо ещё одной реплики на чтение.' },
    { year: '2016', title: 'DevOps как практика', desc: 'Стал связующим звеном между разработкой и эксплуатацией тогда, когда это были разные отделы с разными интересами. Менторил инженеров по обе стороны этой границы.' },
    { year: '2011', title: 'Первый коммит в продакшен', desc: 'PHP-приложение на физическом сервере, деплой по FTP. Работало. Почти. И оно же объяснило, почему сегодня так делать нельзя.' },
  ],
  CTA_TITLE: 'Начать консультацию',
  CTA_SUB: 'Готовы построить нечто экстраординарное? Одно сообщение запускает разговор.',
  FORM: { NAME: 'Ваше Имя', EMAIL: 'Email Адрес', MESSAGE: 'Опишите ваш проект...', SUBMIT: 'Начать консультацию', SUCCESS: '▸ Сообщение отправлено. Я свяжусь с вами в ближайшее время.', PLACEHOLDER_NAME: 'Имя или лучший псевдоним', PLACEHOLDER_EMAIL: 'туда, где живёт идея', PLACEHOLDER_MSG: 'Продукт, команда, мечта — опишите картину...' },
  FORM_ERRORS: {
    NAME_REQUIRED: 'Введите ваше имя',
    NAME_MIN: 'Имя должно содержать минимум 2 символа',
    NAME_MAX: 'Имя слишком длинное',
    NAME_PATTERN: 'Имя содержит недопустимые символы',
    EMAIL_REQUIRED: 'Введите ваш email',
    EMAIL_INVALID: 'Это не похоже на email',
    EMAIL_PATTERN: 'Это не похоже на email',
    MSG_REQUIRED: 'Опишите ваш проект кратко',
    MSG_MIN: 'Сообщение должно содержать минимум 10 символов',
    MSG_MAX: 'Сообщение слишком длинное (макс. 2000)',
    NETWORK: 'Ошибка сети. Попробуйте позже.',
    RATE_LIMIT: 'Не так быстро. По одному сообщению.',
    DELIVERY_DOWN: 'Отсюда отправить не удалось. Напишите напрямую на {mail}.',
  },
  _PAGE_404: {
    TITLE: '404 — Страница не найдена',
    SUB: 'Этот маршрут не существует.',
    CTA: 'Вернуться на главную',
  },
  BIO: 'Пятнадцать лет строю и масштабирую распределённые системы — застал переход индустрии от bare-metal серверов и монолитов к cloud-native, Kubernetes и GitOps. Берусь за то, что команды откладывают: технический долг, CI/CD с нуля и удержание систем в строю.',
  STATS_DESC: 'Миграция инфраструктуры, автоматизация поставки и производительность баз под нагрузкой.',
  ABOUT: 'О себе', CAREER_TITLE: 'Карьера', PROJECTS_TITLE: 'Проекты', ACHIEVEMENTS_TITLE: 'Достижения', SETTINGS: 'Настройки', SETTINGS_LANG: 'Язык', MAIL: 'Почта', THEME_DARK: 'Тёмная', THEME_LIGHT: 'Светлая', MODE_BUSINESS: 'Бизнес', MODE_DESKTOP: 'Рабочий стол', MODE_TERMINAL: 'Терминал',
  COFFEE: { TITLE: '☕ Угостить кофе', NETWORK: 'USDT TRC-20', COPY: 'Скопировать адрес', DONE: '✓ Скопировано', CLOSE: 'Закрыть' },
  DETAIL: { BACK: 'Назад', BACK_CAREER: 'Назад к карьере', BACK_ACH: 'Назад к достижениям', NOT_FOUND: 'не найден', KEY_METRICS: 'Ключевые метрики', FEATURES: 'Возможности', TECH_STACK: 'Технологии', KEY_ACH: 'Ключевые достижения', TYPE_PROJECT: 'Проект', TYPE_CAREER: 'Карьера', TYPE_ACH: 'Достижение', PRIVATE_REPO: 'Приватный репозиторий', OPEN_DETAIL: 'Открыть', REFERENCE_NOTE: 'Референсная архитектура. Клиентский код под NDA, поэтому страница описывает устройство системы и логику решений, а не конкретное внедрение.' },
};

const PONYTAIL = Object.freeze({
  SCRUB: 1, DURATION: 600, EASE: 'power2.inOut',
  CATEGORIES,
  LOCALE: { EN, RU },
  SCENES: [
    { id: 'intro', range: [0, 0.18], label: { EN: '15 Years in Code', RU: '15 лет в коде' }, camera: { position: { from: [0, 0, 22], to: [0, 0, 10] }, fov: { from: 60, to: 46 } }, geometry: { type: 'particleLines', particleCount: 10000, spread: 16, assembleSpeed: 0.6 }, postFX: { bloom: { threshold: 0.5, strength: 1.4, radius: 0.5 }, motionBlur: false }, ambient: { gain: 0.5 } },
    { id: 'chronicle', range: [0.18, 0.35], label: { EN: 'Career Timeline', RU: 'Карьерный путь' }, camera: { position: { from: [0, 0, 10], to: [2, -0.5, 7] }, fov: { from: 46, to: 42 } }, geometry: { type: 'timelineMesh', segments: 15, uiEvolution: true }, postFX: { bloom: { threshold: 0.4, strength: 0.9, radius: 0.35 }, motionBlur: false }, ambient: { gain: 0.45 } },
    { id: 'projects', range: [0.35, 0.62], label: { EN: 'Projects & Impact', RU: 'Проекты и влияние' }, camera: { position: { from: [2, -0.5, 7], to: [0, 0.2, 4.5] }, fov: { from: 42, to: 36 } }, geometry: { type: 'graph3d', nodes: [
      { id: 'go', label: 'Go', group: 'backend', size: 3, color: 0x00add8 },
      { id: 'rust', label: 'Rust', group: 'backend', size: 2.5, color: 0xdea584 },
      { id: 'python', label: 'Python', group: 'backend', size: 3, color: 0xffd43b },
      { id: 'ts', label: 'TypeScript', group: 'lang', size: 2.5, color: 0x3178c6 },
      { id: 'k8s', label: 'Kubernetes', group: 'infra', size: 3, color: 0x326ce5 },
      { id: 'kafka', label: 'Kafka', group: 'infra', size: 2.5, color: 0x231f20 },
      { id: 'postgres', label: 'PostgreSQL', group: 'data', size: 2.5, color: 0x336791 },
      { id: 'redis', label: 'Redis', group: 'data', size: 2, color: 0xdc382d },
      { id: 'pytorch', label: 'PyTorch', group: 'ml', size: 2.5, color: 0xee4c2c },
      { id: 'aws', label: 'AWS', group: 'infra', size: 2.5, color: 0xff9900 },
      { id: 'solidity', label: 'Solidity', group: 'blockchain', size: 2, color: 0x888888 },
      { id: 'react', label: 'React', group: 'frontend', size: 2.5, color: 0x61dafb },
      { id: 'temporal', label: 'Temporal', group: 'infra', size: 2, color: 0x4b7bec },
      { id: 'clickhouse', label: 'ClickHouse', group: 'data', size: 2, color: 0xf0c040 },
      { id: 'flink', label: 'Flink', group: 'infra', size: 2, color: 0x0096d6 },
    ], edges: [
      ['go', 'temporal'], ['go', 'kafka'], ['go', 'postgres'], ['go', 'k8s'],
      ['rust', 'kafka'], ['rust', 'clickhouse'],
      ['python', 'pytorch'], ['python', 'aws'], ['python', 'flink'],
      ['ts', 'react'], ['ts', 'solidity'],
      ['k8s', 'aws'], ['k8s', 'temporal'],
      ['postgres', 'redis'], ['kafka', 'flink'],
      ['pytorch', 'aws'], ['solidity', 'ts'],
    ], cameraPath: 'flythrough' }, postFX: { bloom: { threshold: 0.25, strength: 1.6, radius: 0.55 }, motionBlur: { strength: 0.25 } }, ambient: { gain: 0.5 } },
    { id: 'achievements', range: [0.62, 0.80], label: { EN: 'Milestones', RU: 'Достижения' }, camera: { position: { from: [0, 0.2, 4.5], to: [0.5, 0, 3.8] }, fov: { from: 36, to: 32 } }, geometry: { type: 'achievementNodes' }, postFX: { bloom: { threshold: 0.2, strength: 1.9, radius: 0.5 }, motionBlur: false }, ambient: { gain: 0.35 } },
    { id: 'cta', range: [0.80, 1.0], label: { EN: 'Initiate Consult', RU: 'Начать консультацию' }, camera: { position: { from: [0.5, 0, 3.8], to: [0, 0, 2.5] }, fov: { from: 32, to: 28 } }, geometry: { type: 'terminalUI', terminalLines: 12, scanlineEffect: true, glowIntensity: { from: 1.0, to: 1.6 } }, postFX: { bloom: { threshold: 0.15, strength: 2.2, radius: 0.6 }, motionBlur: false }, ambient: { gain: 0.2, fadeOut: true } },
  ],
  SEO: {
    EN: { title: 'Aleksandr Gribakin — Lead Full Stack & DevOps Engineer', description: 'Fifteen years of full stack and DevOps: bare-metal to cloud-native, Kubernetes and GitOps, CI/CD built from nothing, and databases tuned for highload. Go, Node.js, Python, Terraform.', keywords: 'devops engineer, full stack engineer, kubernetes, terraform, ci/cd, gitops, postgresql, highload, aws, gcp' },
    RU: { title: 'Александр Грибакин — Lead Full Stack & DevOps Engineer', description: 'Пятнадцать лет full stack и DevOps: от bare-metal до cloud-native, Kubernetes и GitOps, CI/CD с нуля и базы данных под highload. Go, Node.js, Python, Terraform.', keywords: 'devops инженер, full stack разработчик, kubernetes, terraform, ci/cd, gitops, postgresql, highload, aws, gcp' },
    structuredData: {
      '@context': 'https://schema.org', '@type': 'Person', name: 'Aleksandr Gribakin', givenName: 'Aleksandr', familyName: 'Gribakin',
      email: 'RF24KRSK@gmail.com', url: 'https://dev24.pro',
      knowsAbout: ['DevOps', 'Kubernetes', 'Infrastructure as Code', 'CI/CD', 'Terraform', 'Ansible', 'Docker', 'PostgreSQL', 'Go', 'Node.js', 'Python', 'React', 'AWS', 'Google Cloud', 'Distributed Systems'],
      // sameAs asserts identity to search engines. The old GitHub URL pointed at
      // an account with zero public repositories. Add profile URLs here only
      // once they are real and yours.
      sameAs: [],
    },
  },
});

export default PONYTAIL;
